### ISSUE TITLE
planner :- Map view button 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1006]
@AmitojSingh1 please discuss  if we need this  MAP VIEW button . then how it works ?

**Comment by AmitojSingh1** [comment]
Map view button basically gets data from ELD and displays the location of trucks nearby. So, put it on hold until we get data from GPS

**Comment by rashmi0301** [comment]
okay sure @AmitojSingh1 paji

**Comment by AmitojSingh1** [comment]
@rashmi0301 as we have no data from ELD could you please comment on the map view button and close the issue.

**Comment by rashmi0301** [comment]
okay
