### ISSUE TITLE
Shift employee ( address book ) into the manage tab 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1011]

**Comment by pankaj-fleethawks** [comment]
Employee shifted in manage tab and redesign the page as UI point of way.. in design link
@rashmi0301  check it
http://design.fleethawks.com/dashboard/add-staff.php

**In dev, now developer need to do this.. Thanks**

**Comment by rashmi0301** [comment]
checked on design 

remove # with the SIN
For user account and other headings -- need some above space so that we know user account is the different section 
button should be cancel save 
if we want to add more address then put plus icon with the clear
 put province instead of state
i guess we need to put the attachment field instead of add picture 
title should be add employee

http://design.fleethawks.com/dashboard/add-staff.php

**Comment by rashmi0301** [comment]
@fleetui i had updated the employee tab fields under the manage tab .. all are done 

could you please remove tab systems over there and please align the fields for the last tab only  . enable login  checkbox is pending . 
i am not able to do this .

**Comment by Hardeep8587** [comment]
@rashmi0301 m on it

**Comment by rashmi0301** [comment]
any update

**Comment by Hardeep8587** [comment]
@rashmi0301 it's done plz test

**Comment by Hardeep8587** [comment]
@rashmi0301 frontend validations are left

**Comment by rashmi0301** [comment]
frontend validations Done
