### ISSUE TITLE
Route :-  Route information 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1019]
when rewrite the locations then previous location under the route information is showing . It should be changed automatically when we rewrite the location and after clicking on add more stops button  then double location is appear . 

![image](https://user-images.githubusercontent.com/79301742/116204420-621e9a00-a75a-11eb-81b8-d5d2f5dd0a35.png)

2. wrong locations are showing .
Scenario is that :- 
I am adding the firstly destination location then this location is appear in first number under the route information . Then i am adding the source location this location is appear in second number under the route information . then after that i am editing the destination location then this location is appear in second  number . so that means my source location is not showing that we had added . And on first number previous destination location is appear . 

kindly figure out this 
![image](https://user-images.githubusercontent.com/79301742/116204705-a4e07200-a75a-11eb-8649-fad55e0262f3.png)

1. if we add biweekly date , this is not in detail page

**Comment by FH-sandeepkaur1** [comment]
Biweekly date thing is not in design. @fleetui please check

**Comment by rashmi0301** [comment]
> Biweekly date thing is not in design. @fleetui please check

@fleetui please discuss if we want then please add on design .. if we don't need it then update here also

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/116658884-4f040800-a9ae-11eb-970d-071ec5e2497c.png)

location is not showing

**Comment by rashmi0301** [comment]
DONE
