### ISSUE TITLE
Driver :- new design of Driver pages - detail , add and list 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1024]
Please update on dev app .. These are approved  Now

**Comment by FH-sandeepkaur1** [comment]
@Daljit-fleetHawks  will do this

**Comment by robinhawks** [comment]
@Daljit-fleetHawks  :- Any timeline when this can be done ??

**Comment by Daljit-fleetHawks** [comment]
> @Daljit-fleetHawks :- Any timeline when this can be done ??

Not Sure @robinhawks . As currently working on ELD

**Comment by rashmi0301** [comment]
design is updated on add form

**Comment by rashmi0301** [comment]
designs are updated
