### ISSUE TITLE
Asset :- please fix these errors 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1033]
![image](https://user-images.githubusercontent.com/79301742/116667781-33066380-a9ba-11eb-975b-d3c0dac48709.png)

**Comment by FH-sandeepkaur1** [comment]
It is the issue of frontend validation. @nameetjambla  will solve it

**Comment by rashmi0301** [comment]
Hi @nameetjambla 

![image](https://user-images.githubusercontent.com/79301742/117011004-3cd1e480-aca2-11eb-9767-0a1a32b27142.png)
this field is not optional but validation message is required . check above 


2. 
![image](https://user-images.githubusercontent.com/79301742/117011083-53783b80-aca2-11eb-8ad2-574c35218299.png)
entered 18 digits alphanumeric but still validations are appear

3. license plate number is 8 digit ?

**Comment by nameetjambla** [comment]
1.@rashmi0301 I have read some articles over the internet and most of them show license plate numbers having 8 digits in them. 
2.In VIN number can you confirm with robin paji because I have read over the internet most of them contain numbers only. 
3.Rest all the above issues will resolve soon.

**Comment by rashmi0301** [comment]
okay @nameetjambla 
now i am clear about the license plate  number

**Comment by rashmi0301** [comment]
please resolve rest

**Comment by nameetjambla** [comment]
@rashmi0301   
1.can you please confirm whether this field is required or optional because In that field there it was written optional but while Saving the entire form there is a validation from the backend which shows that this field is required so i am confused about that.
  
![image](https://user-images.githubusercontent.com/79189939/117704836-f243f100-b1e8-11eb-8a31-26c1472a88c5.png)

**Comment by nameetjambla** [comment]
@rashmi0301  this issue is resolved now you can check

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119200752-692b8600-ba42-11eb-94c0-94ada2743139.png)

1. backend validations 
2. Vin                                                           | it should allow uppercase and numbers only
3. plate number                                           | it should be uppercase letters , space and numbers
4. Height                                                      | height unit is required instead of height type is required
5. length , Premium Amount                       | -  should not allow
6. Reminder Before Expiry                           | e alphabet should not allow and - should not allow

**Comment by nameetjambla** [comment]
@rashmi0301  once my PR is merged then you will check.

**Comment by rashmi0301** [comment]
Asset validations are done
