### ISSUE TITLE
cross border :- Documents 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1038]
please check all the countries related to the documents . do we need all of the countries related to the particular document .

For Birth certificate Documents we only need canada, usa & mexico and their provinces

**Comment by Hardeep8587** [comment]
![image](https://user-images.githubusercontent.com/63697698/116792369-c7b5b200-aadd-11eb-9582-47fbadcdcec4.png)

**Comment by Hardeep8587** [comment]
@rashmi0301 Please mention for all other document type so will apply all at once..

**Comment by Hardeep8587** [comment]
![birth](https://user-images.githubusercontent.com/63697698/116857178-03ee2d00-ac1a-11eb-8f59-15ebcee37803.png)
 This is what I got from border connect itself, other  docs are preferable but they can use this doc incase they need, rest I will do what you recommend for validations and please need to go deep! thank you

**Comment by Hardeep8587** [comment]
@rashmi0301 assign this task to Amitoj also so he should also know about issues.

**Comment by rashmi0301** [comment]
@Hardeep8587 For Birth certificate Documents we only need canada, usa & mexico and their provinces --- this is only for birth certificate . 
as per i talked with @robinhawks . 

as i saw above screenshot i guess we need all countries of birth certificate in future ... please confirm paji

**Comment by Hardeep8587** [comment]
@rashmi0301 birth certificate of passenger or driver?

**Comment by robinhawks** [comment]
@Hardeep8587 
Try asking them from overseas not from North America or try can I travel with my birth certificate from India or any other country (except USA,, Canada, Mexico )if they say yes than you can use it !  which I really doubt it ....whatever the answer is please attach the screen shot 
Thanks !

**Comment by Hardeep8587** [comment]
Yes, passport and license is attached but birth certificate can also be attached for persons as travel document who are out of north america.

**Comment by Hardeep8587** [comment]
@robinhawks It is not used often but if they want to attach along with other document, we will not have option.  please specify for other document types like naturalization, laser visa etc so will do all at once, thanku

**Comment by Hardeep8587** [comment]
@robinhawks @rashmi0301 please make a document of all the validations of cross border, so we should not send wrong data and avoid any delay or penalty, then will apply all to fill valid information only.

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/116872909-a7fcb780-abcb-11eb-9fd1-6d39fe0e0e3d.png)

![image](https://user-images.githubusercontent.com/79301742/116872973-bf3ba500-abcb-11eb-98b4-a7e30a1a1983.png)

@Hardeep8587 please check above 
paji please confirm

**Comment by robinhawks** [comment]
@Hardeep8587 
If you think we need to attach birth certificate go ahead but according to me its not legal way so you can take your decision !
as you have done and documented also so its better you decide 
@rashmi0301 Do as she says she had a word with border connect and also she attached the screen shot so test accordingly 
Thanks

**Comment by Hardeep8587** [comment]
@robinhawks it's not my decision, I always say need another eye to see to make sure it's correct, it's huge, we discuss so we make best product.

**Comment by robinhawks** [comment]
@Hardeep8587 Ok you win ! 
Do one thing we can keep birth certificate as the secondary document but primary must be Passport....
so now if a passenger is travelling they can carry their birth certificate but PASSPORT is Must and it needs to be Primary.....

**Comment by Hardeep8587** [comment]
@robinhawks, Oh bhaji come on,  I was just discussing, I was saying they don't use it often, license and passport is preferable, I mentioned in above document. we need to write code (api most likely) for a document which is rarely used, just a support document of other documents. If we want validation, we must write for other most commonly used  documents like NEXUS card, US visa etc.

**Comment by AmitojSingh1** [comment]
@Hardeep8587 @rashmi0301 is it done or still pending? if pending what's left?

**Comment by Hardeep8587** [comment]
Lets Close it for now, discussed with Robin
