### ISSUE TITLE
Document :- created by date is not appear

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1039]
![image](https://user-images.githubusercontent.com/79301742/116792535-0d3e9480-aa76-11eb-9c63-8a375af80223.png)

and while editing then created by date is not appear

**Comment by FH-sandeepkaur1** [comment]
Please check on new records

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/117041038-60575800-acbf-11eb-9409-18934f536909.png)

new error  occur while editing

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Its working fine

**Comment by rashmi0301** [comment]
working
