### ISSUE TITLE
Design issue :- Route :- UI 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1040]
![image](https://user-images.githubusercontent.com/79301742/116792918-76270c00-aa78-11eb-9cdb-c1bd2d4d6af0.png)

my current typing location should not hide

**Comment by rashmi0301** [comment]
2. please add recurring route date on route detail page on design and then developer will implement on dev 
3. plz add miles on detail page

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119343732-b3cc1e80-bc4b-11eb-9a2f-e7829fbc28cf.png)

plz update the design on design link 
please add recurring route date on route detail page on design and then developer will implement on dev
plz add miles on detail page

**Comment by pankaj-fleethawks** [comment]
All point has been done, check @rashmi0301 and @robinhawks 

http://design.fleethawks.com/dashboard/add-permanent-route.php
http://design.fleethawks.com/dashboard/permanent-route-detail.php

**Comment by robinhawks** [comment]
Test & close the issue @rashmi0301

**Comment by rashmi0301** [comment]
Route information section is updated in Add form 
miles and recurring date is updated on  design link detail page
