### ISSUE TITLE
Order :- Repetition section issue 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1043]
![Screenshot (16)](https://user-images.githubusercontent.com/79301742/116871191-ba292680-abc8-11eb-90c9-cfdeab0c7d3a.png)

1. if we click on add more button , on clicking the shipment 2 then above section of shipment 1 should be close .  Same repetition in detail page also 

2.  if we want to edit the details of the shipment 2 then we click on edit option then shipment 2 details are also opened in shipment   1 . 

3. Temperature unit should be correct . if we select Celsius then both the units showing Celsius
4. while editing delivery instruction is not showing that we had added and consignee is not working properly when we are editing any detail

**Comment by rashmi0301** [comment]
this is the technical issue so developer can do this

**Comment by robinhawks** [comment]
@rashmi0301 @Daljit-fleetHawks  Any update ?

**Comment by Daljit-fleetHawks** [comment]
@robinhawks @rashmi0301 First three points are completed, one left

**Comment by rashmi0301** [comment]
if we click on add more button , on clicking the shipment 2 then above section of shipment 1 should be close . Same repetition in detail page also

if we want to edit the details of the shipment 2 then we click on edit option then shipment 2 details are also opened in shipment 1 .

Temperature unit should be correct . if we select Celsius then both the units showing Celsius

while editing delivery instruction is not showing that we had added and consignee is not working properly when we are editing any detail


done these points
