### ISSUE TITLE
Order :- Order number should not repeat

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1044]
![image](https://user-images.githubusercontent.com/79301742/116874257-e004fa00-abcd-11eb-888e-0a7fca2855e0.png)

if the order is autogenerated then why same number is appear while creating the  order . This was not occurred . but today while creating the order same order number is appear .  

2. while editing the attachment is not showing 
3. on detail page :- currency is not showing with charges

**Comment by FH-sandeepkaur1** [comment]
Please check it in my login. Your login has old orders, i think it is the issue of repetition.

**Comment by rashmi0301** [comment]
DONE
