### ISSUE TITLE
orders :- Not able to save the shipment 2 now 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1061]
![image](https://user-images.githubusercontent.com/79301742/117452149-46ed2080-aef8-11eb-9091-ac1e02687aa1.png)

under the shipment 2 there is no save button of the consignee..

**Comment by robinhawks** [comment]
@Daljit-fleetHawks If the Issue is DONE, Pls comment and let @rashmi0301 know so that she can TEST ......

**Comment by Daljit-fleetHawks** [comment]
@robinhawks Sure, Let me push the code and will ask @rashmi0301 to test

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/120894169-e5d66c80-c5cb-11eb-8881-363089fd5be8.png)

Scenerio is that 


when we  delete the consignee / consignor from top of the del button then still update button was there and i m not able to save the detail .
when we dont want to edit the consignee consignor detail then still update  button was there

**Comment by rashmi0301** [comment]
done
