### ISSUE TITLE
order :- Automatic commodity name is not showing on receiver 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1065]
![image](https://user-images.githubusercontent.com/79301742/117455395-00012a00-aefc-11eb-8370-2d00d19a0563.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 @robinhawks It was occuring due to validation implemented b nameet...he had fixed it now

**Comment by rashmi0301** [comment]
okay @Daljit-fleetHawks  i will check

**Comment by rashmi0301** [comment]
fixed 
commodity is showing automatic
