### ISSUE TITLE
Devices :- New field is added under the fleet but nothing is showing 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1072]
![image](https://user-images.githubusercontent.com/79301742/117544661-542d0c80-afd7-11eb-992c-9334c0527e45.png)

is it functional ?

**Comment by AmitojSingh1** [comment]
I removed this. because the device should come under the manage tab.

**Comment by rashmi0301** [comment]
okay
