### ISSUE TITLE
Vehicle :- Error should occur while selecting  different currencies in payment sections  

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1085]
1. On giving the down payment in usd after that it will give the error on the monthly payment field if user select on cad currrency ( same for purchase) . and on loan tab / insurance tab  :- if our calculations are wrong then error should occur
2. Under the details :- if the premium amount is in Canadian and insurance amount is in USD then error occur or not ?
3. on add page -- please add sliders in a photo section
4.  units in fuels also .. it should be same 
5. Dimensions should have common unit to be decided for Canada --DOT

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
okay

**Comment by rashmi0301** [comment]
after the discussion we dont  want to put auto select currencies in loan and purchase details section ..
These are the optional fields so we gave the flexibility to user that they put anything like USD /CAD
