### ISSUE TITLE
Carrier :- Super admin is not edited and Address issue 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1108]
if we edit he first name and last name then super admin is not edited . 

it occur sometime . earlier it is working . plz figure out this .

2. sometimes mailing and yard address both are appear in home terminal dropdown . I guess only yard address should  appear

**Comment by rashmi0301** [comment]
Not done 

![image](https://user-images.githubusercontent.com/79301742/118714887-cbcd1980-b7d7-11eb-9e63-d1db6b68ca0f.png)

**Comment by Hardeep8587** [comment]
@rashmi0301 I will let u know when my branch is merged,

**Comment by rashmi0301** [comment]
okay

**Comment by rashmi0301** [comment]
i will test the onboard tomm after the validations

**Comment by rashmi0301** [comment]
DONE
