### ISSUE TITLE
Vehicle :- Detail page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1110]
![image](https://user-images.githubusercontent.com/79301742/118325388-3e788500-b4b8-11eb-9d91-f008ff6b8652.png)

1. instead of open issues -- resolved issues are showing 
2. due date is not showing and this is not in reminders also

**Comment by robinhawks** [comment]
@FH-sandeepkaur1 @rashmi0301 

Any Update ??

**Comment by Daljit-fleetHawks** [comment]
@robinhawks first point is done, second is on hold due to work on reminders needs to done by @FH-sandeepkaur1 first...she is working on that

**Comment by rashmi0301** [comment]
instead of open issues -- resolved issues are showing -- DONE 
2.  due date is not showing and this is not in reminders also -- PENDING 

@FH-sandeepkaur1 if you are working on reminders to fetch the data here  then plz look into vehicle reminder also ( strng error occur ) and plz change the subscriber label also from service reminder . if we dont add subscribers and if we add service and vehicle reminder from the plus icon of vehicle detail page then it will redirect to the same page ( vehicle detail) with new details .

**Comment by rashmi0301** [comment]
DONE now
