### ISSUE TITLE
Asset - date is not showing properly 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1111]
![image](https://user-images.githubusercontent.com/79301742/118326733-3a4d6700-b4ba-11eb-9c79-be8ecead5bc7.png)

1. this is in fuels also .. and plz check other modules 
2. Remove cars make and models from the data and keep only for the truck/semi companies

**Comment by sadaf510** [comment]
This is done by me , testing is left

**Comment by Hardeep8587** [comment]
@sadaf510 When u check on dev app, drag it to testing column

**Comment by rashmi0301** [comment]
done
