### ISSUE TITLE
Driver :- issue on new Design 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1114]
owner operator plus icon is missing and it should work properly

**Comment by rashmi0301** [comment]
plus icon with owner operator is not there

**Comment by rashmi0301** [comment]
plus icon is added . 
Data is appear in dropdown when we add entry through plus icon

**Comment by robinhawks** [comment]
@rashmi0301 its updated in devapp but we need to update in design so let know pankaj too @fleetui
