### ISSUE TITLE
Dot point  :- Todays Pick up should route to Planner with all the trips of current date

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1117]
1. adding a permanent route doesn't create trip automatically
2. Todays Pick up should route to Planner with all the trips of current date

**Comment by robinhawks** [comment]
@FH-sandeepkaur1 please do comment if you have worked on it...
@rashmi0301 please update ....and close the isssue !

**Comment by FH-sandeepkaur1** [comment]
1. adding a permanent route doesn't create trip automatically - In add trip when a permanent route is selected then a plan trip is created.
2. Todays Pick up should route to Planner with all the trips of current date - It is redirected to planner and current days trip will be visible on today's date tile on calendar

**Comment by FH-sandeepkaur1** [comment]
> @FH-sandeepkaur1 please do comment if you have worked on it...

I will update only when the PR is merged and I have tested the issues at my end first.

**Comment by rashmi0301** [comment]
1. adding a permanent route doesn't create trip automatically
Answer :- In add trip if we select order option then plan trip is created based on order locations 
if we select route then plan trip is created based on routes location 

2. Todays Pick up should route to Planner with all the trips of current date --- 
Answer :- On overview page if we click on todays pickup it will redirect to the planner page and todays trips will show over the calendar

**Comment by rashmi0301** [comment]
http://devapp.fleethawks.com/#/dispatch/planner/calendar-view
