### ISSUE TITLE
order :- Zero rated field 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1118]
![image](https://user-images.githubusercontent.com/79301742/118372611-6d016900-b567-11eb-8001-1dc90696b15b.png)

1. if we select zero rated then amount should not show 00 at last . This should be applicable on edit page , list , detail page 

2. if we edit the charges then charges calculations are not okay . check below screenshot "News Brunswick " tax is showing 30 .  and options are not showing with charges on detail page that we had choose 

![image](https://user-images.githubusercontent.com/79301742/118403964-c6c86880-b625-11eb-9aea-7021d7b528ce.png)

**Comment by robinhawks** [comment]
@Daljit-fleetHawks @rashmi0301 Any update on this !!!

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
Done
