### ISSUE TITLE
Trips :- Can we show both date and time in Trip info as per the new design 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1133]
if we select order / route .. can we show both date and time 

![image](https://user-images.githubusercontent.com/79301742/118478390-aa2f3d80-b6c4-11eb-8730-f41bcb4c0f55.png)

**Comment by robinhawks** [comment]
@FH-sandeepkaur1 - Please do comment
@rashmi0301  please do the testing and close the issue ....

**Comment by rashmi0301** [comment]
@robinhawks there is no update from dev side . When it's done I will do testing

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119240433-58dbdf80-bb04-11eb-9035-dd58102f7eba.png)

![image](https://user-images.githubusercontent.com/79301742/119240446-6b561900-bb04-11eb-8475-98c7d3e254a3.png)

time and dates are not showing

**Comment by rashmi0301** [comment]
carriers are not showing 
order popup --- customer name is not showing 
if we select order - then consignor consignee name should appear

**Comment by FH-sandeepkaur1** [comment]
> ![image](https://user-images.githubusercontent.com/79301742/119240433-58dbdf80-bb04-11eb-9035-dd58102f7eba.png)
> 
> ![image](https://user-images.githubusercontent.com/79301742/119240446-6b561900-bb04-11eb-8475-98c7d3e254a3.png)
> 
> time and dates are not showing

date is not showing because you have not selected date while adding the stop. 
time is not showing because there will drop off time on stop, not pickup time.

**Comment by rashmi0301** [comment]
done
