### ISSUE TITLE
Trips :- Some changes after schema changes 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1135]
1. when we are on editing page then order number is not showing --- same on detail page 
2. plan trip -- date format and calendar needs to be change 
3. Assigned popup --- driver undefines is showing 

Not able to edit the trip 

4. on detail page it looks like this :- 
![image](https://user-images.githubusercontent.com/79301742/118486915-039c6a00-b6cf-11eb-82e0-194b5462820a.png)

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119240675-1d421500-bb06-11eb-9275-732a43375924.png)

filled all of the data but create trip is not enabled

**Comment by FH-sandeepkaur1** [comment]
It is working @rashmi0301

**Comment by rashmi0301** [comment]
No , this is not working . If we add new entry then button is disabled

**Comment by rashmi0301** [comment]
DONE
