### ISSUE TITLE
planner :- customer name is not showing 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1138]
![image](https://user-images.githubusercontent.com/79301742/118487439-90472800-b6cf-11eb-8db9-d6e4d288ae90.png)

**Comment by robinhawks** [comment]
@rashmi0301 please update......

**Comment by rashmi0301** [comment]
@robinhawks   there is no update  from dev side. So please confirm os it done Or not.

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119459064-360f1e00-bcf2-11eb-9397-4be4aee50b5b.png)
