### ISSUE TITLE
Driver :- issue on new design after schema changes 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1146]
1. Abstract document is not showing on add , edit , detail page 
2. please put province instead of state  -- add , detail , edit page + placeholders
3. citizenship data is not appear -- on list view 
4. Address -- if we are typing any location then only address type and address option should show on detail page . and if we are typing address manually then all fields are showing . --- plz confirm
5. Document section -- remove minus icon 
6.  if we select exempted then cycle  field should not appear on detail page

**Comment by robinhawks** [comment]
@rashmi0301 I explained you already not to make issues in one you should have divided and assigned to them individually unless these issues will be fixed or done in a day !
so make sure this wont happen again !

**Comment by rashmi0301** [comment]
Hi @robinhawks paji, 
Yes, we are decided for adding maximum 4 issues  if they are minor and these issues are minor just need to update text and removing something. These will be fix and done in a day. If there is any major issue then I will create a separate task as we decided.

**Comment by robinhawks** [comment]
@rashmi0301 if these are minor you should try to assign to one developer only

**Comment by robinhawks** [comment]
@Hardeep8587 @FH-sandeepkaur1 @rashmi0301 

How much time will it take to fix these minor issues ! and who is working on which issue I don't have any update on this from anyone ....

**Comment by Hardeep8587** [comment]
@rashmi0301 plz mark which are done, and plz don't put many in one

**Comment by rashmi0301** [comment]
okay

**Comment by rashmi0301** [comment]
citizenship data is not appear -- on list view -- done 
Address -- if we are typing any location then only address type and address option should show on detail page . and if we are typing address manually then all fields are showing . --- we keep as it is

**Comment by Hardeep8587** [comment]
![Uploading image.png…]()

**Comment by rashmi0301** [comment]
DONE all points
