### ISSUE TITLE
Driver :- Issues on new design 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1147]
1. Currencies in payment section -- it should be  like the order . if we select CAD then all currencies should be in CAD
2. document with cross icon is not working -- add , edit , detail page 
3. if select the checkbox of CSA then on edit page  tick is not showing 
4. Home terminal address -- address should not cut off 
5. assign vehicle raw data should not appear -- detail , edit page 
6. date is showing 00 -- detail page 
7. password is not showing -- edit and detail page

**Comment by Hardeep8587** [comment]
@rashmi0301 m on it

**Comment by Hardeep8587** [comment]
Currencies in payment section -- it should be like the order . if we select CAD then all currencies should be in CAD - done
document with cross icon is not working -- add , edit , detail page - working
if select the checkbox of CSA then on edit page tick is not showing - done
Home terminal address -- address should not cut off - done
assign vehicle raw data should not appear -- detail , edit page - done
date is showing 00 -- detail page - not now
password is not showing -- edit and detail page - needs discussion

**Comment by robinhawks** [comment]
@Daljit-fleetHawks 

Try to resolve as much as much as  you can !

**Comment by Hardeep8587** [comment]
@rashmi0301  done

**Comment by rashmi0301** [comment]
done all points
