### ISSUE TITLE
[Border Connect] Error Message is missing in FAST card

### ISSUE THREAD

**Issue by AmitojSingh1** [Fleet-Hawks-Inc/fh-cloud-app#558]
not working as per the place holder instructions + Error should pop-up right away as I am entering the wrong numbers intentionally to test it.
![image (1)](https://user-images.githubusercontent.com/72762922/110693075-478d6300-81a4-11eb-9cdd-150d58cfc484.png)

**Comment by Hardeep8587** [comment]
@rashmi0301 updated on devapp

**Comment by Hardeep8587** [comment]
@rashmi0301  please verify on devapp , its done

**Comment by rashmi0301** [comment]
its done
