### ISSUE TITLE
[border Connect] Issue with add State and add passenger

### ISSUE THREAD

**Issue by AmitojSingh1** [Fleet-Hawks-Inc/fh-cloud-app#559]
Showing + sign is where we are asking them to add state ( I am not comfortable with that) 
Need to find better solution here and Add Document ideally should be with + sign so they can add more documents
Plus the alignment isnt right in design

![image (3)](https://user-images.githubusercontent.com/72762922/110693664-eb770e80-81a4-11eb-9e93-720b99555b1f.png)

**Comment by robinhawks** [comment]
Any updates @fleetui @Hardeep8587

**Comment by Hardeep8587** [comment]
![image](https://user-images.githubusercontent.com/63697698/114013500-3b6cf200-9885-11eb-8f7b-00ad78ae0b99.png)

**Comment by Hardeep8587** [comment]
@rashmi0301 please check on devapp

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/114024751-0c10b200-9892-11eb-9e3e-25aa47e9050d.png)

added plus icon with another document . 
we  will remove the plus icon with state . once we have authentic data
