### ISSUE TITLE
border connect: service is stuck  not able to api

### ISSUE THREAD

**Issue by kunalfleethawks** [Fleet-Hawks-Inc/fh-cloud-app#563]
There is issue when calling border connect api from the cloud app

![image](https://user-images.githubusercontent.com/60139157/110738337-1882fa00-8255-11eb-832d-645b3adce21c.png)

**Comment by kunalfleethawks** [comment]
This has been fixed. there issue with AWS Lambda while connecting to CBSA server. This has been handled by adding code to handle exception. 

Add this exception handling code
```
try {}catch(err){}
```
@gauravfleethawks @rashmi0301 Please test this when it is deployed

**Comment by robinhawks** [comment]
@gauravfleethawks  please check
@rashmi0301  why there was no updates on this ! please explain 

> This has been fixed. there issue with AWS Lambda while connecting to CBSA server. This has been handled by adding code to handle exception.
> 
> Add this exception handling code
> 
> ```
> try {}catch(err){}
> ```
> 
> @gauravfleethawks @rashmi0301 Please test this when it is deployed

**Comment by rashmi0301** [comment]
@AmitojSingh1 is worked on Connectivity . @Hardeep8587 will discussed with @AmitojSingh1 regarding this . Response error

**Comment by AmitojSingh1** [comment]
It's fixed. @rashmi0301 please test.
