### ISSUE TITLE
Address Book :- Add customer form 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#564]
Fields are optional but validation messages are occur . 

![image](https://user-images.githubusercontent.com/79301742/110742528-8da5fd80-825c-11eb-9b96-546dea0e1a48.png)

**Comment by FH-sandeepkaur1** [comment]
It is done on devapp. Please check

**Comment by rashmi0301** [comment]
Remove trailer preference field

**Comment by rashmi0301** [comment]
Its done on dev app . 
we have removed field
