### ISSUE TITLE
Design & Dev  link :- Compare  items  of routing and dispatch for both links 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#565]
Checked listing page and Add forms of overall "Routing and Dispatch"

https://writer.zoho.com/writer/open/borqda986ac2af2664cdeb2c0418addeaa579

**Comment by robinhawks** [comment]
How many issues in one Git number ? please update its pending from a month now @Hardeep8587 @fleetui

**Comment by rashmi0301** [comment]
today i had compared items with both the links some points are still pending 


Order model in design 

1. Searching fields should same -- design 
2. in quantity cases and pallets needs to add -- in design 
3. associated companies fields -- in design 
4. remove launch demo model button --- in design 

Trips tab in design 

1. Searching fields should same -- design 
2. Associate trip to company id -- in design 

Route tab in design 

1. select date field under the recurring is missing -- in design 

planner tab in design 

1. remove searching -- in design 
2. put asset instead of trailer -- in design 

Documents tab in design 

1. remove download button -- in design 
2. download document file option is missing under the actions-- in design 
3. document popup is not open -- in design 

ACE manifest in design 

1. searching fields should same -- in design 
2. asset type is missing -- in design 
3. shipment type options are not same -- in design 

ACI manifest in design 

1. 1. searching fields should same -- in design 
2. asset type is missing -- in design
3.  shipment type options are not same -- in design 

NOTE :- please update number to #
2. please update province instead of state 
3. please update the list view column names labels .. these should be same as per the dev 
4.  please update the buttons also .. 
Scenario is that :- 
on list view page --- put ad button 
on detail page -- put list button 
on add page -- put list button

**Comment by rashmi0301** [comment]
@fleetui is it done or not ..  please update your comment

**Comment by rashmi0301** [comment]
Route tab in design
select date field under the recurring is missing -- in design

planner tab in design :-  
remove searching -- in design
put asset instead of trailer -- in design

Documents tab in design :- 
remove my folder
remove download button -- in design
download document file option is missing under the actions-- in design
document popup is not open -- in design

ACE manifest in design :- 
searching fields should same -- in design

ACI manifest in design :-
searching fields should same -- in design


NOTE :- please update number to #
2. please update province instead of state
3. please update the list view column names labels .. these should be same as per the dev -- cross border
4. searching dropdowns data 
5. plus icons are not working
6. please update the buttons also ..
Scenario is that :-
on list view page --- put ad button
on detail page -- put list button
on add page -- put list button

**Comment by rashmi0301** [comment]
@fleetui please update the items these still pending .

**Comment by robinhawks** [comment]
@Hardeep8587 @fleetui @rashmi0301 

Who is working on which points anyone any Guesses ? its a total mess @rashmi0301 no update from anyone

**Comment by pankaj-fleethawks** [comment]
I am working on this bhaji

**Comment by pankaj-fleethawks** [comment]
@rashmi0301  and @robinhawks 
this issue has been done, @rashmi0301 check all points according sheet, if any point pending then please tell me. Thanks

https://sheet.zoho.com/sheet/open/o8v3557a1cf3086a5430dbfba7e73cb8af90c?sheet=Routing%20issue%20565&range=C41

**Comment by rashmi0301** [comment]
DONE items 

planner tab in design :-
remove searching -- in design
put asset instead of trailer -- in design 

ACE manifest in design :-
searching fields should same -- in design

ACI manifest in design :-
searching fields should same -- in design

Documents tab in design :-
remove my folder
remove download button -- in design
download document file option is missing under the actions-- in design
document popup is not open -- in design

**Comment by pankaj-fleethawks** [comment]
@rashmi0301 done all above point now.. you can check now..

**Comment by rashmi0301** [comment]
DONE
