### ISSUE TITLE
Design & Dev Link :- Compare items of fleet module for design link

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#566]
checked listing view page and all add forms of overall Fleet module 

https://writer.zoho.com/writer/open/ghf0pe394bd768c314d5d80f268d73b706548

**Comment by rashmi0301** [comment]
Driver add form in design  :- 

1. when click on contractor then contractor id field is missing -- design 
2. Default payment type options are not same -- in design 
3. operating zone field is missing --- design 
4.  labels name are not same --- list view in design 

Vehicle Module in design 

1. column visibility options are wrong -- design 
2.  labels name are not same --- list view in design
3. inspection form is missing -- in design 

Asset model in design 

1. height is missing -- in design link 
2. inspection form is missing -- in design 

Fuel model 

1. searching is missing -- in design 
2. payment mode - fuel card option is missing --- in design 
3. plus icon is missing with city and province --- in design 
4. Instead of attach put attach photo  -- design
5. fuel time is missing -- in design 


Vehicle reminder in design 

1. Remove plus icon with the select vehicle -- design 

Issue tab on design

1. different Searching fields are missing -- design 
2. put select vehicle instead of vehicle -- design 
3. remove plus icon with vehicle -- design 
4. when selecting asset then odometer field should not appear --- design

service log in design 

1. group of vehicle need to remove -- design 
2. put select vehicle instead of vehicle -- design 
3. remove plus icon with vehicle -- design 
4. unit type is missing -- in design 
5. put bill# instead of reference -- design 
6. location should remove -- design 
7. remove discount , taxes and subtotal -- design 
8. rate is missing in part section -- in design 
9. please remove s from attach photo and document -- in design
10. different Searching fields are missing -- design 

service program in design 

1. remove primary meters -- in design 

Geofence in design 

1. area is not same to draw geofence -- in design 
 
NOTE :- please update number to #
2. please update province instead of state
3. please update the list view column names labels .. these should be same as per the dev
4. please update the buttons also ..
Scenario is that :-
on list view page --- put ad button
on detail page -- put list button
on add page -- put list button

**Comment by rashmi0301** [comment]
@fleetui checked the items some tabs are done but some are pending .. please check above

**Comment by robinhawks** [comment]
@fleetui please update the status as the issue is pending from almost last 40 days !

**Comment by rashmi0301** [comment]
Driver add form in design :-
when click on contractor then contractor id field is missing -- design
Default payment type options are not same -- in design
labels name are not same --- list view in design

Asset model in design :- 
inspection form is missing -- in design

Fuel 
searching fields should be same like dev 
attach field label is not clear - add form

 reminder :- 
 approx last date and odometer field - service reminder 
now plz remove  email notification checkbox for all tabs 
Searching fields should  be same 

Service log :- 
There should be vehicle asset radio buttons like devapp
remove location 
put bill# instead of reference -- design
location should remove -- design
remove discount , taxes and subtotal -- design
rate is missing in part section -- in design
please remove s from attach photo and document -- in design
different Searching fields are missing -- design

service program in design:- 
remove primary meters -- in design

Geofence in design
area is not same to draw geofence -- in design

NOTE :- please update number to #
2. please update province instead of state
3. please update the list view column names labels .. these should be same as per the dev
4. please update the buttons also ..
Scenario is that :-
on list view page --- put ad button
on detail page -- put list button
on add page -- put list button

**Comment by rashmi0301** [comment]
@fleetui plz check make all of the items  should be same on add page

**Comment by rashmi0301** [comment]
entire fleet page is different is design so plz it should be same as per the dev app

**Comment by robinhawks** [comment]
@fleetui Almost 35 points in one Git issue .......How many are done can you at least comment on this !

**Comment by pankaj-fleethawks** [comment]
All above points has been done
Check now @rashmi0301 and @robinhawks 

Check following sheet
https://sheet.zoho.com/sheet/open/o8v3557a1cf3086a5430dbfba7e73cb8af90c?sheet=Sheet1&range=F21

**Comment by rashmi0301** [comment]
okay @fleetui

**Comment by rashmi0301** [comment]
all items are in add add forms under the design link
