### ISSUE TITLE
Address Book -- Search

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#567]
Searching is not working

**Comment by robinhawks** [comment]
Any update ?? @FH-sandeepkaur1

**Comment by FH-sandeepkaur1** [comment]
It is working except the Caps issue that you have pointed. I'm going to work on it today. Will be updating soon regarding this.

**Comment by rashmi0301** [comment]
Company name searching is working whether we put the text in caps or small then suggestions are occur ..

but

this is not working on name field -- if we are putting full name in caps and small then no data is appear

**Comment by rashmi0301** [comment]
Now text in caps and small then suggestion are appear .. we can select through suggestions then searching is working .
done on dev
