### ISSUE TITLE
Add Trip: Overlapping Search location

### ISSUE THREAD

**Issue by AmitojSingh1** [Fleet-Hawks-Inc/fh-cloud-app#570]
Location search is overlapping on ADD trip page 

![overlapingSearch](https://user-images.githubusercontent.com/72762922/110845142-7ddfe680-8267-11eb-953d-8f85a540a1d2.PNG)

**Comment by FH-sandeepkaur1** [comment]
this point is done

**Comment by rashmi0301** [comment]
DONE
