### ISSUE TITLE
DOT points :- Trips

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#572]
We should be able to edit the trip from its Detailed View Page ( Edit Functionality is not working )
not able to add even

**Comment by FH-sandeepkaur1** [comment]
It is working on cloudapp

http://cloudapp.fleethawks.com/#/dispatch/trips/add-trip

**Comment by FH-sandeepkaur1** [comment]
cloud app code is not updated. it is working on dev app. please check and close if it is working

**Comment by rashmi0301** [comment]
DONE ON dev
