### ISSUE TITLE
Routing and Dispatch :- Compare Ui for overall Routing and dispatch module for both links 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#584]
In this sheet i had checked overall UI  for add form pages , detail view pages and listing view pages and also compare the UI for both the links . please check the attached document and  resolve the issues .

sheet link is :- https://sheet.zoho.com/sheet/open/nhkfra7ae5e9ba6014f55a838dbb3ba38970f?sheet=order&range=A1

**Comment by AmitojSingh1** [comment]
@rashmi0301 and @fleetui any updates on this?

**Comment by rashmi0301** [comment]
@AmitojSingh1 we need to fix the alignments and spacing issues for overall entire solution .. Designer knows that

**Comment by rashmi0301** [comment]
i will create separate sheet for this
