### ISSUE TITLE
Fleet :- Compare UI for overall fleet module of both links ( design & dev )

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#587]
In this sheet i had compared both the links ( design and dev ) as a UI prospective . 
check :- https://sheet.zoho.com/sheet/open/5zygt770f9f89f8b140e8869b9d332f390e83?sheet=driver%20&range=A3

**Comment by robinhawks** [comment]
@fleetui any updates ?

**Comment by rashmi0301** [comment]
we need to fix the alignments and spacing issues for overall entire solution .. Designer knows that

**Comment by rashmi0301** [comment]
please update here

**Comment by rashmi0301** [comment]
i will create a separate sheet for this
