### ISSUE TITLE
Driver Dashboard Screen 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#590]
Fix the dropdown 

![image](https://user-images.githubusercontent.com/79301742/111415508-1367f400-8708-11eb-8c44-ae02b3985c59.png)

**Comment by pankaj-fleethawks** [comment]
Resolved this issue, but PR pending for merge, I will update you @rashmi0301 when it will merge and will live on dev.

![image](https://user-images.githubusercontent.com/63699936/111423371-37cacd00-8716-11eb-9d28-10cbab9e8d8a.png)

**Comment by rashmi0301** [comment]
This is DONE
