### ISSUE TITLE
Wrong Side Navbar

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#591]
![image](https://user-images.githubusercontent.com/79301742/111418930-8d9b7700-870e-11eb-93de-a06280fa5fec.png)

**Comment by robinhawks** [comment]
@Daljit-fleetHawks update why it is taking too long !

**Comment by rashmi0301** [comment]
Done

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/114165464-24440800-994a-11eb-8e0b-bf8c3b521e81.png)


@FH-sandeepkaur1 it happens sometime . can you just figure out

**Comment by rashmi0301** [comment]
Any update ?

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/118376066-98da1a00-b57a-11eb-9cf0-ab4bcba760dc.png)

**Comment by robinhawks** [comment]
@rashmi0301  Any update ? why it is taking too long.... @Daljit-fleetHawks

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Please share all test cases

**Comment by rashmi0301** [comment]
Done 

tested on firefox , chrome , edge 

it happens sometime .  Discussed with @kunalfleethawks regarding this
