### ISSUE TITLE
Address Book 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#592]
DBA name should be optional for all tabs 
Company name should be required for all tabs

**Comment by rashmi0301** [comment]
DBA name is in Broker , customer  and this is not optional . please put optional text over there . 

DBA name is missing in other tabs ?

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 any  update ?

**Comment by FH-sandeepkaur1** [comment]
it is done

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/114167110-2e670600-994c-11eb-89f1-e9d2aecdf5c6.png)
![image](https://user-images.githubusercontent.com/79301742/114167138-3757d780-994c-11eb-85d2-2eb9a25fdad1.png)

DBA is not updated as optional . 
Dba is not in other tabs

**Comment by rashmi0301** [comment]
DONE
