### ISSUE TITLE
Remove radio buttons from our dashboard and put buttons (rectangle) over there .

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#593]
![image](https://user-images.githubusercontent.com/79301742/111420747-c8eb7500-8711-11eb-93c5-e53ae4dbf995.png)

**Comment by robinhawks** [comment]
please update pankaj @fleetui

**Comment by rashmi0301** [comment]
done

**Comment by rashmi0301** [comment]
broker is pending

**Comment by pankaj-fleethawks** [comment]
done this issue @rashmi0301 .. check at your end

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115691255-83a70c80-a37b-11eb-8be5-b3b23f59dbc8.png)

**Comment by rashmi0301** [comment]
On models

**Comment by rashmi0301** [comment]
any update ?

**Comment by rashmi0301** [comment]
done now
