### ISSUE TITLE
Address Book - Pagination 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#596]
![image](https://user-images.githubusercontent.com/79301742/111428980-4e752200-871e-11eb-9086-1d57484ec3d2.png)

**Comment by FH-sandeepkaur1** [comment]
the -ve count issue is resolved. @rashmi0301 
I'm working on the point - pagination issue while deleting. will update you regarding this

**Comment by rashmi0301** [comment]
the -ve count issue is done 
Okay

**Comment by FH-sandeepkaur1** [comment]
Please check @rashmi0301

**Comment by rashmi0301** [comment]
i will be check address by TOMM . today im working on other modules

**Comment by rashmi0301** [comment]
pagination is working 
this is also working when we delete the entry
