### ISSUE TITLE
Address Book :- Employee

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#601]
Wrong success message is appear 

![image](https://user-images.githubusercontent.com/79301742/111431929-63ec4b00-8722-11eb-9b50-7795392ec278.png)

**Comment by FH-sandeepkaur1** [comment]
@rashmi0301 please check it on dev app

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/111866733-92259100-8995-11eb-93e1-60b669c935fb.png)


STILL SHOWING

**Comment by rashmi0301** [comment]
any update @FH-sandeepkaur1

**Comment by FH-sandeepkaur1** [comment]
I was not working on address book issues. going to work on them today. will update you @rashmi0301

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115027022-ccc11180-9ee0-11eb-8c42-ec6716be9184.png)

**Comment by FH-sandeepkaur1** [comment]
@Hardeep8587 will fix role related issues

**Comment by rashmi0301** [comment]
now we will removed the employee
