### ISSUE TITLE
Geofence :- Add form 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#610]
![image](https://user-images.githubusercontent.com/79301742/111447864-dade0f80-8733-11eb-934a-cad7b69e0b5c.png)

**Comment by pankaj-fleethawks** [comment]
@rashmi0301 Done this point, but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
DONE
