### ISSUE TITLE
Inventory listing page :- Not able to search the items, category and vendor . Success message should be " Inventory deleted Successfully " . Transfer button where the data should save

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#613]
Not able to search the items, category and vendor 
success message should be " Inventory deleted Successfully "
transfer button where the data should save

![image](https://user-images.githubusercontent.com/79301742/111454011-2f848900-873a-11eb-9811-9d2d2c2fee21.png)

**Comment by FH-sandeepkaur1** [comment]
Please check it on devapp @rashmi0301

**Comment by rashmi0301** [comment]
WORKING FINE
