### ISSUE TITLE
Service log :- Searching is not working and success should appear properly on Listing page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#615]
1. success messages should be "Service log added successfully"
2. select task field is not working 
![image](https://user-images.githubusercontent.com/79301742/111460744-547cfa00-8742-11eb-9ae6-7cf70c57dd47.png)

**Comment by FH-sandeepkaur1** [comment]
searching is working. please check and update @rashmi0301

**Comment by rashmi0301** [comment]
done
