### ISSUE TITLE
PlaceHolders

### ISSUE THREAD

**Issue by robinhawks** [Fleet-Hawks-Inc/fh-cloud-app#617]
@rashmi0301 
![image](https://user-images.githubusercontent.com/79191245/111461924-cdc91c80-8743-11eb-9173-cdb5d8b084f9.png)

**Comment by robinhawks** [comment]
@rashmi0301  please update

**Comment by rashmi0301** [comment]
@robinhawks 

@fleetui designer will do this then i will update

**Comment by robinhawks** [comment]
@fleetui  pankaj update this !

**Comment by rashmi0301** [comment]
DONE
