### ISSUE TITLE
Trip :- Add trip 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#621]
on clicking the location field then popup appear . it should remove 

please check all fields @fleetui popups are different 

![image](https://user-images.githubusercontent.com/79301742/111467168-226f9600-874a-11eb-8c1e-3bb49b8c7b33.png)

**Comment by pankaj-fleethawks** [comment]
Done this point, @rashmi0301 check it.. 
http://design.fleethawks.com/dashboard/create-trip.php

**Comment by rashmi0301** [comment]
please check in dev and fix the width of the popup for all 

![image](https://user-images.githubusercontent.com/79301742/111859340-4ad3dc00-8966-11eb-8a80-827e3fc8aefc.png)

**Comment by rashmi0301** [comment]
@fleetui  any update ?
