### ISSUE TITLE
Date format should be "yyyy-mm-dd" should be small letters . It should be everywhere 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#623]

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done on driver/asset/geofence/maintenance.

**Comment by FH-sandeepkaur1** [comment]
it is done in dispatch too. Please check and let us know if it is pending somewhere.

i'm working in address book regarding the same

**Comment by rashmi0301** [comment]
Done on driver/asset/geofence/maintenance.

Done on trips , Cross border only ..
but placeholder format is pending

**Comment by rashmi0301** [comment]
Except orders module -- NOT DONE 

Rest is updated

**Comment by rashmi0301** [comment]
DONE 

all are on dev

**Comment by rashmi0301** [comment]
Hello team , as per the discussion with kunal we need to show the slash in between the format in frontend and - in backend .
format is fine now . but please put slash in frontend

**Comment by rashmi0301** [comment]
@sadaf510  is it done ?

**Comment by rashmi0301** [comment]
1. vehicle - list page  -- hyphine is showing 
2. fuel - list page -- 00 is showing 
3. ace/aci  -- aci  hyphine is showing  
4. driver -- page didnt open

**Comment by robinhawks** [comment]
@FH-sandeepkaur1 please comment if its done so @rashmi0301 can test and close the issue

**Comment by rashmi0301** [comment]
okay i will test tomorrow

**Comment by rashmi0301** [comment]
changes are still not reflected on dev app

**Comment by rashmi0301** [comment]
This is done on whole solution
