### ISSUE TITLE
Move Carrier Switch Button under Main login dropdown 

### ISSUE THREAD

**Issue by FHAdmin** [Fleet-Hawks-Inc/fh-cloud-app#625]
![image](https://user-images.githubusercontent.com/58348391/111531135-c137ca80-8729-11eb-924c-fd7b800c5997.png)

Also we need to ensure that it is shown only for the companies that has signed up as multiple carriers  or else it shouldn't show up at all

**Comment by FH-sandeepkaur1** [comment]
Now we are not switching the carrier.

**Comment by rashmi0301** [comment]
okay
