### ISSUE TITLE
Search Functionality not working under Driver List Page 

### ISSUE THREAD

**Issue by FHAdmin** [Fleet-Hawks-Inc/fh-cloud-app#626]
![image](https://user-images.githubusercontent.com/58348391/111531560-4de28880-872a-11eb-9917-e60b80d0d2a1.png)

After putting "Rashmi" as driver , the cloudapp is not filtering the drivers + even if you hit "Search " button, nothing happened

**Comment by FH-sandeepkaur1** [comment]
Now it is working in both cases except the duty status part. I'm working on it
case 1 - If you directly types the name and hit the search button.
case 2 - when you are selecting it from the suggestions.

Please check @rashmi0301  on devapp.

**Comment by rashmi0301** [comment]
case 1 - If you directly types the name and hit the search button.
case 2 - when you are selecting it from the suggestions.

Working fine on dev

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 if we write full name in caps and small then searching not working

**Comment by rashmi0301** [comment]
If we are putting the text in caps and small then selecting from suggestion then searching is working
