### ISSUE TITLE
Issue tab :- It should be Vehicle / Asset

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#632]
![image](https://user-images.githubusercontent.com/79301742/111581729-cce5c880-87df-11eb-82fd-fc3380562ed4.png)

**Comment by pankaj-fleethawks** [comment]
Done this point @rashmi0301 , but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
DONE

**Comment by rashmi0301** [comment]
http://devapp.fleethawks.com/#/fleet/maintenance/issues/list
