### ISSUE TITLE
Asset :- spell check in popup on Add form 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#633]
![image](https://user-images.githubusercontent.com/79301742/111582296-a1171280-87e0-11eb-80af-2cfad3a9d9d4.png)

**Comment by pankaj-fleethawks** [comment]
Done this point @rashmi0301  , but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
Done

http://devapp.fleethawks.com/#/fleet/assets/add
