### ISSUE TITLE
Asset :- Searching is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#634]
![image](https://user-images.githubusercontent.com/79301742/111584091-6b275d80-87e3-11eb-89d4-3cf0a1df60dd.png)

I want to search the container type in " select type" field but options is not there

**Comment by FH-sandeepkaur1** [comment]
resolved. Please check it @rashmi0301 

![image](https://user-images.githubusercontent.com/72725109/112269686-b38cc280-8c9e-11eb-91cb-37a1396fe419.png)

**Comment by rashmi0301** [comment]
working
