### ISSUE TITLE
Rough data ( asset type)  should not appear 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#636]
![image](https://user-images.githubusercontent.com/79301742/111586544-fe15c700-87e6-11eb-853b-5ac9b05288d9.png)

1. Two way commands - Temperature should be in degree 
2. what type of devices are there

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
not done

**Comment by rashmi0301** [comment]
Done
