### ISSUE TITLE
Reminder tab :- success message should be like " service reminder added, deleted , updated successfully " for all tabs 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#638]
![image](https://user-images.githubusercontent.com/79301742/111590278-ea209400-87eb-11eb-969d-af14fb7e0338.png)

**Comment by Hardeep8587** [comment]
@rashmi0301 it's updated on devapp plz check

**Comment by rashmi0301** [comment]
DONE
