### ISSUE TITLE
Vehicle renewal :- spacing issue 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#640]
![image](https://user-images.githubusercontent.com/79301742/111594704-69649680-87f1-11eb-8bf9-86789618e76e.png)

**Comment by pankaj-fleethawks** [comment]
Done this point @rashmi0301 , but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
DONE

http://devapp.fleethawks.com/#/fleet/reminders/vehicle-renewals/add
