### ISSUE TITLE
Add form vehicle :- plus icon with assign driver not working .

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#644]
Not able to add driver 

![image](https://user-images.githubusercontent.com/79301742/111598803-987d0700-87f5-11eb-8894-1ec862f7ae4d.png)

**Comment by Daljit-fleetHawks** [comment]
Done @rashmi0301

**Comment by rashmi0301** [comment]
Working now

**Comment by rashmi0301** [comment]
not able to add driver model 
home terminal data is not appear 

![Screenshot (9)](https://user-images.githubusercontent.com/79301742/112754273-2f815600-8f90-11eb-81ae-008a1cb34cf1.png)

**Comment by rashmi0301** [comment]
@Daljit-fleetHawks  any update

**Comment by rashmi0301** [comment]
working

**Comment by rashmi0301** [comment]
Not working ..

**Comment by rashmi0301** [comment]
yes this is working both assign driver / driver's team 
working fine driver if we put old email , username , cdl , sin
