### ISSUE TITLE
Vehicle :- Raw data is  showing  in listing view page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#646]
![image](https://user-images.githubusercontent.com/79301742/111601326-412c6600-87f8-11eb-9cb2-ae6097e8db3a.png)

**Comment by gauravfleethawks** [comment]
It is because of deleted relation data in the database.

**Comment by rashmi0301** [comment]
Then remove  the fuel types from add form of fuel tab 

so that raw data should not appear 

![image](https://user-images.githubusercontent.com/79301742/111859441-01d05780-8967-11eb-9b32-d782ae1ff1c3.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 We can't remove any field from any form 😄 . raw data will not appear here. Its fixed now

**Comment by robinhawks** [comment]
@rashmi0301 - this issue is baseless.... there was no need to re-open this issue...........Please review do we need to remove fuel type from the form 

> Then remove the fuel types from add form of fuel tab
> 
> so that raw data should not appear
> 
> ![image](https://user-images.githubusercontent.com/79301742/111859441-01d05780-8967-11eb-9b32-d782ae1ff1c3.png)

**Comment by rashmi0301** [comment]
@Daljit-fleetHawks  yes we can't remove but as per we discussed we need same fuel type options in vehicle model also. Coz options are not same and raw data is appear that's why i reopened the issue @robinhawks 

![image](https://user-images.githubusercontent.com/79301742/113972227-ee265b80-9857-11eb-819d-1d04b25abe70.png)

now its fine . same options are appear
