### ISSUE TITLE
It should be start date in vehicle detail page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#648]
![image](https://user-images.githubusercontent.com/79301742/111603726-a41efc80-87fa-11eb-8ec3-e0e6d0481e8c.png)

**Comment by gauravfleethawks** [comment]
done

**Comment by rashmi0301** [comment]
DONE 
http://devapp.fleethawks.com/#/fleet/vehicles/detail/6c003020-87c9-11eb-aa7d-a18f6018fd79
