### ISSUE TITLE
Raw data is appear in fuel tab on vehicle detail page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#649]
![image](https://user-images.githubusercontent.com/79301742/111604036-eb0cf200-87fa-11eb-88b8-472fcfd0dd5b.png)

**Comment by gauravfleethawks** [comment]
Again relation data deleted from the database.

**Comment by rashmi0301** [comment]
Then remove the fuel types from add form of fuel tab

so that raw data should not appear

**Comment by rashmi0301** [comment]
done
