### ISSUE TITLE
Vehicle :- Fields are not in add form but showing in detail view page  

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#650]
![image](https://user-images.githubusercontent.com/79301742/111604263-2d363380-87fb-11eb-8cb0-12f0c7a6e692.png)

1. last two fields are not in add form in this tab 
2. it should be loan .

**Comment by gauravfleethawks** [comment]
@rashmi0301 done

**Comment by rashmi0301** [comment]
DONE 

http://devapp.fleethawks.com/#/fleet/vehicles/list
