### ISSUE TITLE
validation messages should appear only for required  fields 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#652]
![image](https://user-images.githubusercontent.com/79301742/111606729-961eab00-87fd-11eb-9ba3-e0d817001a70.png)

**Comment by Daljit-fleetHawks** [comment]
![image](https://user-images.githubusercontent.com/67137586/111613994-1d235180-8805-11eb-91a9-b39f8f42a78a.png)

Please do hard refresh before checking on dev link @rashmi0301 ...Its already there

**Comment by rashmi0301** [comment]
done
