### ISSUE TITLE
Quantity should not be in negative in our product 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#653]
for example 

![image](https://user-images.githubusercontent.com/79301742/111608490-47721080-87ff-11eb-8d14-26fc3cdba147.png)

**Comment by gauravfleethawks** [comment]
done

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/111859571-d1d58400-8967-11eb-8aef-b3e0446b78b9.png)
![image](https://user-images.githubusercontent.com/79301742/111859577-dac65580-8967-11eb-9694-4a6178ca977c.png)

Guys , this should be applicable for overall tabs ( Add forms) under the fleet module .

**Comment by gauravfleethawks** [comment]
@rashmi0301 done for vehicle

**Comment by rashmi0301** [comment]
done for vehicle

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done on asset. I will update this if find same field on another module.

**Comment by rashmi0301** [comment]
DONE ON ASSET 

Any update for other modules @Hardeep8587 @Daljit-fleetHawks @FH-sandeepkaur1 @gauravfleethawks

**Comment by AmitojSingh1** [comment]
Which modules are left?

**Comment by rashmi0301** [comment]
DONE for all
