### ISSUE TITLE
Driver is not added

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#654]
![image](https://user-images.githubusercontent.com/79301742/111609061-ea2a8f00-87ff-11eb-9fe5-9b6ac898ff23.png)

**Comment by AmitojSingh1** [comment]
@rashmi0301 Is it resolved?

**Comment by rashmi0301** [comment]
Working added driver over a new record

**Comment by rashmi0301** [comment]
Not working 
Not able to add , edit

**Comment by rashmi0301** [comment]
new design for driver is implementing by @Hardeep8587 

same for driver model

**Comment by Hardeep8587** [comment]
m working on new design and database schema

**Comment by rashmi0301** [comment]
driver is added
