### ISSUE TITLE
Onboard screen 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#655]
![image](https://user-images.githubusercontent.com/79301742/111613793-e9e0c280-8804-11eb-9931-5a44677239f4.png)

**Comment by pankaj-fleethawks** [comment]
Done this point @rashmi0301 , but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
DONE 

http://devapp.fleethawks.com/#/onboard
