### ISSUE TITLE
Login Screen 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#659]
![image](https://user-images.githubusercontent.com/79301742/111617075-aee08e00-8808-11eb-95ca-160da5733606.png)

1. Correct validation message  should appear 

something like :- please enter the username and password 

2. Forgot password is missing 
3. Eye icon is missing so that we can view or hide the password

**Comment by AmitojSingh1** [comment]
Submitted the PR @rashmi0301 please review it.

**Comment by rashmi0301** [comment]
@AmitojSingh1 if i entered wrong password and correct username then validation message should be please enter valid password. 
same for username . 
and when i had entered the correct username and password then this error occur

 " 2 validation errors detected: Value 'rashmicloud ' at 'userName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+; Value 'rashmicloud ' at 'userAlias' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+"

how about forgot password?

**Comment by rashmi0301** [comment]
any update ?

**Comment by nameetjambla** [comment]
@robinhawks paji  @rashmi0301 Frontend Validations are updated now .

**Comment by rashmi0301** [comment]
1. button should be disabled  -- pending

Now we had applied only required validation . 
if we entered the incorrect username and password -- then only this message is appear "Incorrect username or password."
as per the discussion with @FH-sandeepkaur1 @Hardeep8587 we are not applying the pattern validations

**Comment by rashmi0301** [comment]
if we want to edit the username on login screen then button should be enable

**Comment by rashmi0301** [comment]
Done 

now if we dont fill any credentials then button disable is showing 
if we fill credentials then button is enable and if we want to edit then button is also enable 

For validations 
Now we had applied only required validation .
if we entered the incorrect username and password -- then only this message is appear "Incorrect username or password."
and only touched dirty validation is appear
