### ISSUE TITLE
Login screen 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#660]
1. sign up line should be in center and having proper top bottom space . 
2. same for login 
![image](https://user-images.githubusercontent.com/79301742/111617550-45ad4a80-8809-11eb-8e60-c89f0862c2f0.png)

**Comment by pankaj-fleethawks** [comment]
Done this point @rashmi0301 , but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
Done . spacing is now consistent from top bottom to the login text

http://devapp.fleethawks.com/#/Login
