### ISSUE TITLE
On clicking the company profile , 404 error  occur 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#661]
![image](https://user-images.githubusercontent.com/79301742/111618002-dedc6100-8809-11eb-820a-915a2f334e8b.png)

**Comment by Daljit-fleetHawks** [comment]
@fleetui Please design this page and account setting page.

**Comment by rashmi0301** [comment]
now on clicking the company profile the company detail page is open
