### ISSUE TITLE
On clicking the account setting , it just refresh the page and redirect to homepage . There should be the particular page ( account setting) 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#662]
![image](https://user-images.githubusercontent.com/79301742/111618318-3d094400-880a-11eb-9a25-9dc5d0dbca06.png)

**Comment by rashmi0301** [comment]
On clicking the account setting , nothing happens

**Comment by FH-sandeepkaur1** [comment]
It is because this section is not developed yet.

**Comment by rashmi0301** [comment]
okay

**Comment by rashmi0301** [comment]
Account setting is removed now .. 
on clicking the company profile -- then we will redirect to the company profile page .. 

NOTE:- The old usernames don't have the data in their carrier tables they entered directly in the users and this function requires carrier ID . when you do it for a new carrier then it works .
