### ISSUE TITLE
Driver placeholder text :- spell wrong 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#663]
![image](https://user-images.githubusercontent.com/79301742/111619491-a8074a80-880b-11eb-9cdc-d4830b3e1b9f.png)

**Comment by Daljit-fleetHawks** [comment]
Done @rashmi0301

**Comment by rashmi0301** [comment]
DONE 

![image](https://user-images.githubusercontent.com/79301742/111859644-5922f780-8968-11eb-871b-2baa924d9999.png)

**Comment by rashmi0301** [comment]
http://devapp.fleethawks.com/#/fleet/drivers/add
