### ISSUE TITLE
Driver add form :-  Citizenship name spell check 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#666]
![image](https://user-images.githubusercontent.com/79301742/111621005-74c5bb00-880d-11eb-9955-9442dd39781d.png)
![image](https://user-images.githubusercontent.com/79301742/111621875-7e035780-880e-11eb-83c4-e6f3fd3fe36b.png)
![image](https://user-images.githubusercontent.com/79301742/111622063-be62d580-880e-11eb-8ff6-02a856f3cac9.png)

Rest are pending

**Comment by Daljit-fleetHawks** [comment]
Done @rashmi0301

**Comment by rashmi0301** [comment]
done 
Rest are pending . "a" "b" alphabets are done i had matched from google

**Comment by rashmi0301** [comment]
Please correct germany , iran , ivory coast
