### ISSUE TITLE
Vehicle :- This should be add vehicle renewal reminder 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#667]
![image](https://user-images.githubusercontent.com/79301742/111625170-91b0bd00-8812-11eb-92f6-50a57b4aadaf.png)

**Comment by gauravfleethawks** [comment]
We are already in vehicle detail. So no need to add vehicle everywhere.

**Comment by rashmi0301** [comment]
okay
