### ISSUE TITLE
geofence - searching is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#671]
![image](https://user-images.githubusercontent.com/79301742/111762080-99319e00-88c6-11eb-8545-6bc70b36f283.png)
****

**Comment by FH-sandeepkaur1** [comment]
This point is done. Please review @rashmi0301

**Comment by rashmi0301** [comment]
DONE . 
searching is working in case sensitive also
