### ISSUE TITLE
geofence - spacing issue 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#672]
![image](https://user-images.githubusercontent.com/79301742/111763626-6092c400-88c8-11eb-81ff-aedaad4380b6.png)

**Comment by pankaj-fleethawks** [comment]
@rashmi0301 Done this point, but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
Done
