### ISSUE TITLE
geofence :- alignment issue 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#673]
![image](https://user-images.githubusercontent.com/79301742/111763851-989a0700-88c8-11eb-8d9a-9738fbb15bb1.png)

**Comment by pankaj-fleethawks** [comment]
@rashmi0301 Done this point, but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
DONE 

http://devapp.fleethawks.com/#/fleet/geofence/add
