### ISSUE TITLE
Inventory :- Put red stars on the popups and add forms . This should be applicable for whole product 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#674]
Those are required fields please put red stars over there 

![image](https://user-images.githubusercontent.com/79301742/111765803-d13ae000-88ca-11eb-8c14-e50a2e209ad6.png)

**Comment by pankaj-fleethawks** [comment]
done this issue, so check @rashmi0301

**Comment by rashmi0301** [comment]
This is not done for all popups ... we need to implement the red star and optional text for all models and plus icons popups

**Comment by rashmi0301** [comment]
Done for models and add form .. updated the required and optional fields

**Comment by nameetjambla** [comment]
@rashmi0301 this issue is complete and fixed you can check now
