### ISSUE TITLE
Inventory :- address is not popping up 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#675]
![image](https://user-images.githubusercontent.com/79301742/111766095-22e36a80-88cb-11eb-9a64-d631443d4cb6.png)

**Comment by FH-sandeepkaur1** [comment]
The user is selecting country, state and city itself so it is a manual address and location suggestions should not be there

**Comment by rashmi0301** [comment]
okay
