### ISSUE TITLE
fix the UI . This type of issue occurs in whole product 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#678]
![image](https://user-images.githubusercontent.com/79301742/111766654-cc2a6080-88cb-11eb-9642-4f51c20632aa.png)

1. This type of issue occur in address  book also

**Comment by AmitojSingh1** [comment]
I think it's fixed. Please check and close @rashmi0301

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/114559016-ec5dfd00-9c88-11eb-9388-444011a98e46.png)

still have

**Comment by rashmi0301** [comment]
![Uploading image.png…]()

**Comment by pankaj-fleethawks** [comment]
Ya its done.. already.. at my end this is okay @rashmi0301

**Comment by pankaj-fleethawks** [comment]
![image](https://user-images.githubusercontent.com/63699936/115459849-2610a400-a245-11eb-8e8e-40801a9eca2e.png)

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115510455-60a62b00-a29d-11eb-84aa-d0ebfc9744d8.png)

**Comment by rashmi0301** [comment]
rest is okay

**Comment by pankaj-fleethawks** [comment]
yes rashmi.. I checked and done which were pending
@rashmi0301  check

**Comment by rashmi0301** [comment]
done
