### ISSUE TITLE
Pagination issues for whole product

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#682]
@FH-sandeepkaur1 please check for fleet module sometimes this type pagination is appear 

![image](https://user-images.githubusercontent.com/79301742/111767780-22e46a00-88cd-11eb-8683-8883a719f82d.png)

**Comment by FH-sandeepkaur1** [comment]
this point is done. please review @rashmi0301

**Comment by rashmi0301** [comment]
when delete then this type pagination occur 

![image](https://user-images.githubusercontent.com/79301742/114165601-4fc6f280-994a-11eb-8ea9-dfe4d5b87aff.png)

**Comment by FH-sandeepkaur1** [comment]
Please check @rashmi0301

**Comment by rashmi0301** [comment]
Now when we delete the entry pagination is also working fine
