### ISSUE TITLE
For whole product - Add photo , document is optional or required 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#683]
![image](https://user-images.githubusercontent.com/79301742/111767972-56bf8f80-88cd-11eb-959c-19704368555d.png)

**Comment by AmitojSingh1** [comment]
@rashmi0301 Is it a topic of discussion?  or it's an issue?

**Comment by pankaj-fleethawks** [comment]
@robinhawks bhaji please confirm that attach input will be optional or required (mandate) ??

**Comment by robinhawks** [comment]
@fleetui  Make it Optional ....

**Comment by rashmi0301** [comment]
@sadaf510  please do it for a entire solution

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/118361057-8510c280-b53e-11eb-89f9-b3dc7ee56c7f.png)

someone is added type . plz remove this

**Comment by sadaf510** [comment]
The issue is resolved.

**Comment by rashmi0301** [comment]
This is done 

applied optional to all
