### ISSUE TITLE
Service log :- On clicking the browser back button from vehicle page the 404 errors occur 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#687]
![image](https://user-images.githubusercontent.com/79301742/111773509-46f77980-88d4-11eb-86fe-1d68b39a128e.png)

**Comment by AmitojSingh1** [comment]
@rashmi0301 It's working here. what's the link it's redirecting to? could you please check and review.

**Comment by rashmi0301** [comment]
@AmitojSingh1  if we click on the issue link on the list view page of service log then again click on asset / vehicle name then again click on browser back button then 404 error occur . if it is still not clear then let me know

**Comment by rashmi0301** [comment]
404 error issue is resolved
