### ISSUE TITLE
Service log :- remove the $ and fix the spacing issue 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#689]
![image](https://user-images.githubusercontent.com/79301742/111773958-d43ace00-88d4-11eb-8b84-f57ef78ea73f.png)

**Comment by rashmi0301** [comment]
1. vendor data is not appear in dropdown when we add

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
DONE
