### ISSUE TITLE
Add input arrows in odometer field for whole product

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#691]
![image](https://user-images.githubusercontent.com/79301742/111774986-2e885e80-88d6-11eb-8728-39aca17ad87f.png)

**Comment by AmitojSingh1** [comment]
@rashmi0301 On which page this error is created?

**Comment by rashmi0301** [comment]
> @rashmi0301 On which page this error is created?

@AmitojSingh1  this is in whole product where the odometer field occur . because n some of the fields there are input arrows and in some field there are no input arrows . so i just want to make consistent for whole product in same field .

**Comment by AmitojSingh1** [comment]
Could you please specify the particular page which need changes and individually create a new issue do that we can't miss anything.

**Comment by rashmi0301** [comment]
okay yeah . 
Regarding the odometer label and input arrows . i had discussed with @Hardeep8587 
@Hardeep8587 please update what we do

**Comment by FH-sandeepkaur1** [comment]
any update regarding this @rashmi0301 ?

**Comment by rashmi0301** [comment]
we need to enter the number .. not input arrows and added validation over there . as per the discussion with @Hardeep8587 
This is for whole solution where the odometer fields are there

**Comment by rashmi0301** [comment]
please update guys

**Comment by rashmi0301** [comment]
done
