### ISSUE TITLE
Service program :- title text should be in black in detail view page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#694]
![image](https://user-images.githubusercontent.com/79301742/111775426-bec6a380-88d6-11eb-9be1-3bbe4c431753.png)

**Comment by AmitojSingh1** [comment]
@rashmi0301 I didn't find this page. Could you please refer me Which page is this?

**Comment by rashmi0301** [comment]
this is the detail page of service program 
go to add service schedule then popup is appear 
and go to add vehicle button then popup is appear

**Comment by FH-sandeepkaur1** [comment]
please add placeholders in these @rashmi0301 

![image](https://user-images.githubusercontent.com/72725109/115380670-701b6a80-a1f0-11eb-9af5-389cf392a4dc.png)

**Comment by rashmi0301** [comment]
Done placeholders

**Comment by rashmi0301** [comment]
DONE
