### ISSUE TITLE
Service program :- plus icon of vehicle model - Fuel type options are different 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#695]
![image](https://user-images.githubusercontent.com/79301742/111776597-3b0db680-88d8-11eb-8aee-4a6913bffe94.png)

**Comment by rashmi0301** [comment]
Vehicle modal is not working

**Comment by rashmi0301** [comment]
Vehicle Model is working

**Comment by Daljit-fleetHawks** [comment]
> Vehicle Model is working

Please select manufacturer first then you will able to see those

**Comment by AmitojSingh1** [comment]
@rashmi0301 Is it resolved?

**Comment by rashmi0301** [comment]
DONE
