### ISSUE TITLE
Issue tab :- Searching is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#697]
![image](https://user-images.githubusercontent.com/79301742/111777494-60e78b00-88d9-11eb-8ff4-a72a0bcc0dfb.png)

**Comment by Hardeep8587** [comment]
@rashmi0301 Sandeep is working on search, to make it case insensitive

**Comment by FH-sandeepkaur1** [comment]
Please check on devapp @rashmi0301

**Comment by rashmi0301** [comment]
DONE 
Except search by issue name

**Comment by FH-sandeepkaur1** [comment]
Issue name also done. Please check

**Comment by rashmi0301** [comment]
DNE ON ISSUE TAB
