### ISSUE TITLE
Reminders :- Searching is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#700]
![image](https://user-images.githubusercontent.com/79301742/111778471-b4a6a400-88da-11eb-99c8-cb64abdb78bc.png)

**Comment by Hardeep8587** [comment]
@rashmi0301 please check I updated on devapp

**Comment by rashmi0301** [comment]
1. Searching is not working if i am putting full name in caps   , without selecting from suggestions . ( rather it is company name and carrier name ) -- then No data found is appear
--
2. if user had entered the first word  in caps and rest are small then searching should work
3. Without entering anything in search box then click on Search button. error should occur
4. Enter only special characters in search field and click on Search button. error should occur

**Comment by rashmi0301** [comment]
DONE
