### ISSUE TITLE
vehicle :- what is the purpose of these fields in detail page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#704]
![image](https://user-images.githubusercontent.com/79301742/111782264-cf7b1780-88de-11eb-9b72-ca40bf529f74.png)

**Comment by gauravfleethawks** [comment]
@rashmi0301 As discussed in group meeting..We will gonna remove it for the time .

**Comment by rashmi0301** [comment]
REMOVED
