### ISSUE TITLE
Add trip :- location is not poping up 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#707]
![image](https://user-images.githubusercontent.com/79301742/111859320-27a92c80-8966-11eb-9c00-d23bab8eac48.png)

**Comment by pankaj-fleethawks** [comment]
Done this point @rashmi0301 , but PR merge to be pending, so check it tomorrow morning at dev link
http://devapp.fleethawks.com/#/dispatch/trips/add-trip
