### ISSUE TITLE
These should be number so add # . This should be applicable for whole address Book 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#713]
![image](https://user-images.githubusercontent.com/79301742/111866156-6accc500-8991-11eb-82ff-ba64f2eb0bff.png)

**Comment by FH-sandeepkaur1** [comment]
noted

**Comment by AmitojSingh1** [comment]
@rashmi0301 Is it fixed?

**Comment by rashmi0301** [comment]
detail pages are pending 
carrier  page

**Comment by rashmi0301** [comment]
DONE
