### ISSUE TITLE
Address Book :- Searching is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#714]
![image](https://user-images.githubusercontent.com/79301742/111866199-d57e0080-8991-11eb-9fab-b148a593ebb4.png)

Check for all tabs

**Comment by FH-sandeepkaur1** [comment]
this point is done. Please review @rashmi0301

**Comment by rashmi0301** [comment]
Scenario:-

Searching is working in Case sensitive . if i am putting text in Caps and small letters . then suggestions are appear . --- This is FINE .
Searching is not working if i am putting full name in caps and full name in small letter . ( rather it is company name and carrier name ) -- then No data found is appear

**Comment by rashmi0301** [comment]
Company name searching is working whether we put the text in caps or small then suggestions are occur ..

but 

this is not working on name field -- if we are putting full name in caps and small then no data is appear

**Comment by rashmi0301** [comment]
Now searching is working when we are selecting from suggestions for all in both cases simple and case sensitive
