### ISSUE TITLE
Pagination issue occurs in Address book after deleted , edited the entry 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#715]
![image](https://user-images.githubusercontent.com/79301742/111866397-2e9a6400-8993-11eb-93a6-11c26dfb1e08.png)

**Comment by FH-sandeepkaur1** [comment]
please check @rashmi0301

**Comment by rashmi0301** [comment]
Today  Im working on other module will check address book by tomm .

**Comment by rashmi0301** [comment]
This is done
