### ISSUE TITLE
When we tick the enable login option then 4 options are not showing in detail view age 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#717]
![image](https://user-images.githubusercontent.com/79301742/111866659-fbf16b00-8994-11eb-9233-0e6de8ba7d22.png)

Employee

**Comment by FH-sandeepkaur1** [comment]
this point is done. Please review @rashmi0301

**Comment by rashmi0301** [comment]
employee tab is not working

**Comment by FH-sandeepkaur1** [comment]
for now we are removing employee from address book

**Comment by rashmi0301** [comment]
okay
