### ISSUE TITLE
Owner operator :-  when we select the option from payroll type field then further miles options are not appear 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#721]
![image](https://user-images.githubusercontent.com/79301742/111867171-622bbd00-8998-11eb-8d78-12337e18768d.png)

not able to select currency as well

**Comment by FH-sandeepkaur1** [comment]
it is done

**Comment by rashmi0301** [comment]
Pay per hour and pay per mile options should  same as per driver

**Comment by FH-sandeepkaur1** [comment]
it will remain as it is as discussion with @Hardeep8587

**Comment by rashmi0301** [comment]
okay
