### ISSUE TITLE
Orders :- Searching is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#725]
![image](https://user-images.githubusercontent.com/79301742/111941994-61aa3800-8af8-11eb-9d91-c8520c5ed88f.png)

**Comment by FH-sandeepkaur1** [comment]
some of the fields are changed. will update you once it is done

**Comment by rashmi0301** [comment]
Order number searching filter is not working

**Comment by FH-sandeepkaur1** [comment]
Please test the filters by adding new enteries

**Comment by rashmi0301** [comment]
NOT WORKING  checked over the new record

**Comment by rashmi0301** [comment]
task is created already
