### ISSUE TITLE
Order listing page :- spacing should be fix and width of the column should be consistent 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#729]
![image](https://user-images.githubusercontent.com/79301742/111943047-9dde9800-8afa-11eb-90aa-55b29aade1ef.png)

**Comment by pankaj-fleethawks** [comment]
the height of the row and the width of the column can not same, because it totally depends on content @rashmi0301

**Comment by pankaj-fleethawks** [comment]
@rashmi0301 Done this point, but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/112140601-3576e000-8bfa-11eb-9f6e-a0baed147fe3.png)
DONE
