### ISSUE TITLE
Add orders page :- If we click on yes in a " will driver load" then where is the payment 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#730]
![image](https://user-images.githubusercontent.com/79301742/111946187-0466b480-8b01-11eb-9fb0-5adde51de330.png)

**Comment by gauravfleethawks** [comment]
@rashmi0301 Its not in design ..if we want to add the option for payment for driver load or unload..then we need to add the in design first .

**Comment by rashmi0301** [comment]
OKAY

**Comment by FH-sandeepkaur1** [comment]
@rashmi0301  are there any changes regarding this?

**Comment by rashmi0301** [comment]
if we select the driver load "yes" then payments should appear .@robinhawks please give us the suggestions or we can hold for now ?

**Comment by rashmi0301** [comment]
if he(s) is the employee of the contractor then payment will goes to the contractor amount ..
