### ISSUE TITLE
Add Order :- Extra commodity and other extra fields should be open below the plus icon 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#732]
![image](https://user-images.githubusercontent.com/79301742/111947800-1f86f380-8b04-11eb-8ae3-6a1f3459e789.png)

**Comment by gauravfleethawks** [comment]
@rashmi0301 done

**Comment by rashmi0301** [comment]
@gauravfleethawks  what about the other fields . " accessorial fee " " accessorial deduction "

**Comment by gauravfleethawks** [comment]
@rashmi0301 done

**Comment by rashmi0301** [comment]
DONE
