### ISSUE TITLE
Orders:- Put red star over there

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#733]
![image](https://user-images.githubusercontent.com/79301742/111947893-42b1a300-8b04-11eb-9194-b5ee880230ea.png)

**Comment by pankaj-fleethawks** [comment]
@rashmi0301  Done this point, but PR pending to submit and merge, will do it later today..

**Comment by rashmi0301** [comment]
Done
