### ISSUE TITLE
Add order :- In details address is not showing 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#737]
![image](https://user-images.githubusercontent.com/79301742/111949886-7e01a100-8b07-11eb-87eb-b2de5168fdd6.png)

**Comment by gauravfleethawks** [comment]
@rashmi0301 Because that respective customer does not have the shipment address. Those who have the shipment address saved will be shown here.

**Comment by rashmi0301** [comment]
Phone number , country address is not showing

**Comment by rashmi0301** [comment]
address is showing in detail page
