### ISSUE TITLE
Orders :- Launch Modal section is not updated 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#738]
![image](https://user-images.githubusercontent.com/79301742/111950197-f8cabc00-8b07-11eb-9053-372fca33b219.png)

**Comment by gauravfleethawks** [comment]
@rashmi0301 This is for PDF automation. We are making a new page for it... It is no used for the time.

**Comment by rashmi0301** [comment]
okay so we are hold for now
