### ISSUE TITLE
Consignor :- Data is not showing in dropdown That i had recently added .

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#740]
![image](https://user-images.githubusercontent.com/79301742/111950964-03d21c00-8b09-11eb-9a7d-018dc6e4304b.png)

**Comment by gauravfleethawks** [comment]
@gauravfleethawks done

**Comment by rashmi0301** [comment]
DONE
now it is showing in dropdown
http://devapp.fleethawks.com/#/dispatch/orders/add
