### ISSUE TITLE
Inventory edit page :- Im adding the  multiple photos but is not showing in photos section. 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#746]
![image](https://user-images.githubusercontent.com/79301742/111956216-87433b80-8b10-11eb-8f4d-914ea0bd588e.png)

**Comment by gauravfleethawks** [comment]
![image](https://user-images.githubusercontent.com/60806972/112103620-077ca600-8bd0-11eb-8f9a-1dbdd6215194.png)

@rashmi0301 It's working fine for multiple photos...

**Comment by rashmi0301** [comment]
DONE 
http://devapp.fleethawks.com/#/fleet/inventory/detail/bb301fc0-8bca-11eb-bbe7-073a133a9df5
