### ISSUE TITLE
Reminder :- Searching is not working for all

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#753]
![image](https://user-images.githubusercontent.com/79301742/111966163-9b8d3580-8b1c-11eb-94ab-43e0a2944394.png)

**Comment by FH-sandeepkaur1** [comment]
this point is done. Please review on dev-app @rashmi0301

**Comment by rashmi0301** [comment]
Working now 
except last field . @Hardeep8587 is working on development part

**Comment by rashmi0301** [comment]
Last field is working now . 

1. Searching is not working if i am putting full name in caps   , without selecting from suggestions . ( rather it is company name and carrier name ) -- then No data found is appear
--
2. if user had entered the first word  in caps and rest are small then searching should work
3. Without entering anything in search box then click on Search button. error should occur
4. Enter only special characters in search field and click on Search button. error should occur

**Comment by rashmi0301** [comment]
DONE
