### ISSUE TITLE
Asset :- Raw data should not appear in "Type field " , " vendor field " . Fix the unit of the length it should FEET . 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#755]
![image](https://user-images.githubusercontent.com/79301742/111967919-9cbf6200-8b1e-11eb-9484-061eb86d125a.png)

1. temperature should be in degrees --- need to remove now 
2. where the temperature comes from ? --- need to remove now 
3.  devices are come from ?  --- need to remove now

**Comment by rashmi0301** [comment]
Date of expiry , reminders are not showing 

![Screenshot (11)](https://user-images.githubusercontent.com/79301742/112756103-6b201e00-8f98-11eb-9dd7-8c94b29d8c44.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
DONE
