### ISSUE TITLE
Vehicle :- service program model , fix the UI

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#757]
![image](https://user-images.githubusercontent.com/79301742/111971832-ca0e0f00-8b22-11eb-9f46-ab83c58f2934.png)

**Comment by rashmi0301** [comment]
Description field size should be large 

![image](https://user-images.githubusercontent.com/79301742/112754440-f72e4780-8f90-11eb-945c-91861f91377e.png)

**Comment by pankaj-fleethawks** [comment]
done this issue @rashmi0301 check..

**Comment by rashmi0301** [comment]
done

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/116030703-cf0e3300-a679-11eb-85ce-488730fa9056.png)

Repeat by time fields should have some space

**Comment by rashmi0301** [comment]
@nameetjambla  please do it for a small task .. please add a space 

![image](https://user-images.githubusercontent.com/79301742/118119481-4692d080-b3a3-11eb-82b9-139e3a7fa8a6.png)

**Comment by nameetjambla** [comment]
@rashmi0301  this issue is resolved now once my updated pr is merged you can check.

**Comment by nameetjambla** [comment]
@rashmi0301  you can check now this issue is resolved

**Comment by rashmi0301** [comment]
done .. thanks @nameetjambla
