### ISSUE TITLE
Vehicle 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#758]
![image](https://user-images.githubusercontent.com/79301742/111972793-d6df3280-8b23-11eb-90a4-95fb2c431d77.png)

**Comment by gauravfleethawks** [comment]
@rashmi0301 done

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/112143989-9d2f2a00-8bfe-11eb-8320-911088ab6357.png)

NOW IN THIS FIELD VALIDATION MESSAGE OCCUR

**Comment by gauravfleethawks** [comment]
@rashmi0301 done

**Comment by rashmi0301** [comment]
DONE
