### ISSUE TITLE
order :- pagination is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#760]

**Comment by FH-sandeepkaur1** [comment]
@rashmi0301 Please attach the screenshot or video so that I would know where the issue is and which part is not working.

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 when we delete the entry then accurate pagination is not showing

**Comment by rashmi0301** [comment]
Today i m working on address book part .. will check Dispatch by tomm

**Comment by rashmi0301** [comment]
task is already created
