### ISSUE TITLE
Trips :- Searching is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#763]
![image](https://user-images.githubusercontent.com/79301742/112108029-b66fb080-8bd5-11eb-9ca1-4f029091d038.png)

**Comment by FH-sandeepkaur1** [comment]
It is done. PR is not merged yet. will update you one merged. @rashmi0301 

To check this please add new records. It might not work on old data.

**Comment by rashmi0301** [comment]
this is only working in a trip type and and trip number ..

else options in searching is not working

**Comment by FH-sandeepkaur1** [comment]
please check by creating new records

**Comment by rashmi0301** [comment]
order number filter is not working 

![image](https://user-images.githubusercontent.com/79301742/115111820-d8274200-9f9f-11eb-913e-bb6fb11b1929.png) --- same for vehicle , asset

Date searching , trip number , trip type -- working

**Comment by rashmi0301** [comment]
BUT why upper trip list is showing WHERE THERE IS NO DRIVER , VEHCILE , ASSET

**Comment by rashmi0301** [comment]
task is already created

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/116882176-fbc1cd80-abd8-11eb-95f0-5a823fec9e00.png)

**Comment by FH-sandeepkaur1** [comment]
Please check by creating new record

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/117042097-669a0400-acc0-11eb-9c33-736395cd3d2e.png)


not working in case sensitive .. checked over new record

**Comment by FH-sandeepkaur1** [comment]
It is working

**Comment by rashmi0301** [comment]
This is working
