### ISSUE TITLE
Trips :- Date searching is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#764]
![image](https://user-images.githubusercontent.com/79301742/112108400-2aaa5400-8bd6-11eb-92c9-b5b358e06884.png)

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/114712853-2e9d4200-9d4e-11eb-817d-d765aea2c6f4.png)

there are two trips in a selected date but trips are not showing

**Comment by FH-sandeepkaur1** [comment]
please search by adding new records

**Comment by rashmi0301** [comment]
order number filter is not working 

![image](https://user-images.githubusercontent.com/79301742/115111820-d8274200-9f9f-11eb-913e-bb6fb11b1929.png) --- same for vehicle , asset

Date searching , trip number , trip type -- working

**Comment by FH-sandeepkaur1** [comment]
![image](https://user-images.githubusercontent.com/72725109/115112219-1d4c7380-9fa2-11eb-906c-db2082d94988.png)

because driver elina is assigned to this trip

**Comment by rashmi0301** [comment]
> order number filter is not working
> 
> ![image](https://user-images.githubusercontent.com/79301742/115111820-d8274200-9f9f-11eb-913e-bb6fb11b1929.png) --- same for vehicle , asset
> 
> Date searching , trip number , trip type -- working

but why upper trip list is showing ??

**Comment by rashmi0301** [comment]
Filters are working . checked over the new records

**Comment by rashmi0301** [comment]
On detail page :- 

1. stops are static 
2. empty loaded is not showing whether we had added 
3. total miles should . check below screenshot 
![image](https://user-images.githubusercontent.com/79301742/115858555-bbca5000-a44c-11eb-9db4-fcb7bdb39176.png)

@fleetui 
4. Multiple attachments are not added . only single attachment is showing . and wen we  upload the PDF then broken doc is showing 
5. search is in design .. if we have more trips then we need search over there . 
6. @fleetui  can you fix this box for week and day . its looks not good . columns and row are tight . need some little spacing 
![image](https://user-images.githubusercontent.com/79301742/115861321-4c565f80-a450-11eb-8342-9e59bebde78a.png)

**Comment by rashmi0301** [comment]
On detail page :-

stops are static -- DONE 
empty loaded is not showing whether we had added -- NOT DONE
total miles should show  .  --NOT DONE 
if we are adding the carrier in add form while creating the trip then this is not showing on detail page .   -- NOT DONE

**Comment by rashmi0301** [comment]
@fleetui 
![image](https://user-images.githubusercontent.com/79301742/116228943-905ca380-a773-11eb-8161-3abbad67886e.png)

1. Broken PDF is showing . 
2. if we want to replace the image with other then how can we do that ?
3. search is in design .. if we have more trips then we need search over there .
4. @fleetui can you fix this box for week and day . its looks not good . columns and row are tight . need some little spacing

**Comment by rashmi0301** [comment]
empty loaded is not showing whether we had added -- DONE 
total miles should show . --DONE

fix the BOL/POD message  --- NOT DONE

**Comment by rashmi0301** [comment]
DONE
