### ISSUE TITLE
Trip :- AM PM should be show 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#766]
![image](https://user-images.githubusercontent.com/79301742/112109196-43673980-8bd7-11eb-965b-99419129dc1f.png)

**Comment by FH-sandeepkaur1** [comment]
@rashmi0301  24 hour format is used here while selecting time. so no need of am/pm

**Comment by rashmi0301** [comment]
OKAY
