### ISSUE TITLE
Order :- Will driver load if it is yes then "yes" should show. If it is NO then "no" should show 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#770]
![image](https://user-images.githubusercontent.com/79301742/112111724-98587f00-8bda-11eb-8c8a-bb6a3ba11cc7.png)

**Comment by gauravfleethawks** [comment]
@rashmi0301 done

**Comment by rashmi0301** [comment]
Done 

we need a payment section when driver unload option is "yes" 

@fleetui

**Comment by rashmi0301** [comment]
payment is in owner operator as discussed @robinhawks
