### ISSUE TITLE
Order :- Advanced Received is different  

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#772]
![image](https://user-images.githubusercontent.com/79301742/112112882-19644600-8bdc-11eb-9408-efa4803af5a1.png)

**Comment by gauravfleethawks** [comment]
@rashmi0301 
The table 'Advance Received' is static right now . we are not saving the advance received anywhere in the system yet .

**Comment by rashmi0301** [comment]
okay
