### ISSUE TITLE
Route :- Driver and co driver model - Home terminal is not showing .

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#777]
![image](https://user-images.githubusercontent.com/79301742/112126718-bcbc5780-8bea-11eb-9c6c-391025a7bd83.png)

2. vehicle model not working

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done.

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/112616785-25553f80-8e4a-11eb-91cc-271b42861812.png)
not done

**Comment by Daljit-fleetHawks** [comment]
![image](https://user-images.githubusercontent.com/67137586/112617878-89c4ce80-8e4b-11eb-8d2b-60f4372a953c.png)

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/112798742-348ee580-9022-11eb-9f14-1316a95bab53.png)

**Comment by Hardeep8587** [comment]
Home terminal is yard address that we put when we onboard a carrier! we can't get unless we go through whole process

**Comment by rashmi0301** [comment]
This is working now ..  
Home terminal is a yard address . 
We can find through onboard pages

**Comment by rashmi0301** [comment]
models are not working now 
Driver and CO-driver

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
models are not updated with new design . Once its updated then i will start testing over there

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Sure....as Hardeep is working on updating new design..once she finish it then all modals will get update

**Comment by rashmi0301** [comment]
modals are working now
