### ISSUE TITLE
Route :- Icons move to this side 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#779]
![image](https://user-images.githubusercontent.com/79301742/112128029-05284500-8bec-11eb-9f87-5fc0a15b70b2.png)

Route stop text should be aligned .

**Comment by rashmi0301** [comment]
Need some space 

![image](https://user-images.githubusercontent.com/79301742/112128827-ce9efa00-8bec-11eb-9304-f0b104fa08f3.png)

**Comment by pankaj-fleethawks** [comment]
> Need some space
> 
> ![image](https://user-images.githubusercontent.com/79301742/112128827-ce9efa00-8bec-11eb-9304-f0b104fa08f3.png)

Done this issue @rashmi0301

**Comment by rashmi0301** [comment]
> ![image](https://user-images.githubusercontent.com/79301742/112128029-05284500-8bec-11eb-9f87-5fc0a15b70b2.png)

not done

**Comment by rashmi0301** [comment]
any update

**Comment by rashmi0301** [comment]
@fleetui kindly update ? 
why it is taking so long ?

**Comment by rashmi0301** [comment]
@nameetjambla as i discussed with @fleetui route information section  will change .. we will add the stop maximum 10 stops .. with the location name .

**Comment by pankaj-fleethawks** [comment]
@rashmi0301 @robinhawks @FH-sandeepkaur1 it is done, you can check on design link and implement it into dev link. Thanks

http://design.fleethawks.com/dashboard/create-trip.php

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 please discuss with @fleetui and same thing will be implement on trips and route

**Comment by robinhawks** [comment]
@rashmi0301 Any update ??

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119203539-1b198100-ba48-11eb-812d-0199e59e99a7.png)

it is not done ..  if its done from devs side then i'll do

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119238305-9afe2480-baf6-11eb-9456-4f64451c8528.png)

Now the destination icon is at last and source icon is at first

check above screenshot i had added 10 stops with multiple states .
