### ISSUE TITLE
Route :- I Had added the stop but stop location and description  is not showing in route information 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#780]
![image](https://user-images.githubusercontent.com/79301742/112129304-4b31d880-8bed-11eb-9a73-16c3cf91f6bc.png)

**Comment by FH-sandeepkaur1** [comment]
It is designed in this way. Only source and destination points are supposed to be there. Please discuss it with @robinhawks  or @FHAdmin and let me know if there are any changes

**Comment by FH-sandeepkaur1** [comment]
@fleetui please update

**Comment by rashmi0301** [comment]
@fleetui any update

**Comment by FH-sandeepkaur1** [comment]
Will implement once it is fixed in trips, as they both are having same design.

**Comment by rashmi0301** [comment]
any update

**Comment by FH-sandeepkaur1** [comment]
it is still pending @rashmi0301 
@fleetui  please check

**Comment by pankaj-fleethawks** [comment]
please wait @FH-sandeepkaur1 i will do it asap... and @rashmi0301 this is technical so i will handle it. you can do another issue.. leave this issue...

**Comment by rashmi0301** [comment]
okay @fleetui paji .

**Comment by robinhawks** [comment]
@fleetui any update
@rashmi0301 why this is taking too long !!

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119203587-3b494000-ba48-11eb-83e2-ed02fde0d070.png)


we are not getting the stop location on route information . once its done from dev side then i will do 
@robinhawks

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119238305-9afe2480-baf6-11eb-9456-4f64451c8528.png)


Now we are showing the multiple stops with horizontal scroll --- DONE 
Now we are showing states with the stops in route information . --- DONE 

check above screenshot i had added 10 stops with multiple states .
