### ISSUE TITLE
Route :- Miles are not showing in detail view page, listing view page and add form page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#782]

**Comment by FH-sandeepkaur1** [comment]
done in listing and add/edit page. Please check @rashmi0301 

detail view design is pending

**Comment by FH-sandeepkaur1** [comment]
@fleetui  please update miles in route detail page.

**Comment by rashmi0301** [comment]
DONE 
miles are showing in list view and add / edit page 

![image](https://user-images.githubusercontent.com/79301742/114390499-fbbf4680-9bb3-11eb-848f-032f7e86a0b5.png)

**Comment by rashmi0301** [comment]
miles are not in detail page . so @fleetui can you update miles on design link first

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 you can directly implemented the miles on detail page .. as per the discussion with @FHAdmin

**Comment by rashmi0301** [comment]
Today i m working on address book part .. will check Dispatch by tomm

**Comment by rashmi0301** [comment]
done
