### ISSUE TITLE
Route :- why these buttons are appear 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#783]
![image](https://user-images.githubusercontent.com/79301742/112129744-bbd8f500-8bed-11eb-85ff-24ce236c41fd.png)

Instead of these there should " All Routes " and " Add route " button

**Comment by FH-sandeepkaur1** [comment]
This point is done. Please review @rashmi0301

**Comment by rashmi0301** [comment]
Done
