### ISSUE TITLE
Route :- Route information notes are not showing in detail view page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#785]
![image](https://user-images.githubusercontent.com/79301742/112133785-0ceae800-8bf2-11eb-94c7-de2e0d708673.png)
![image](https://user-images.githubusercontent.com/79301742/112133826-170ce680-8bf2-11eb-9983-2a429aa9469e.png)

**Comment by FH-sandeepkaur1** [comment]
This points is done. please review @rashmi0301

**Comment by rashmi0301** [comment]
DONE
