### ISSUE TITLE
order:- If there are more photos then need to add slider arrows / dots 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#787]
![image](https://user-images.githubusercontent.com/79301742/112137584-6f45e780-8bf6-11eb-9426-392a8b18ae5e.png)

**Comment by FH-sandeepkaur1** [comment]
Maximum 4 images/docs will be uploaded for now. So no need of slider

**Comment by rashmi0301** [comment]
currently i am adding pdfs .. broken PDFs are showing . not able to download .

**Comment by FH-sandeepkaur1** [comment]
@rashmi0301  please check this in order and trip detail page. Now only files with jpeg, jpg, png, pdf will be uploaded in bol/pod

**Comment by rashmi0301** [comment]
okay 
but now i m uploading the PDF and JPEG files success message is -- BOL updated successfully . 
it should be BOL/POD updated successfully

**Comment by rashmi0301** [comment]
now we only add 4 attachments (png, PDF, jpeg)
and success message is now BOL/POD
