### ISSUE TITLE
Driver :- Address is not poping up in emergency  tab

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#793]
![image](https://user-images.githubusercontent.com/79301742/112286682-90b7d980-8cb1-11eb-9a03-8a1a7b225173.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Address suggestions not needs to be appear here.

**Comment by rashmi0301** [comment]
OKAY
