### ISSUE TITLE
Driver :- profile image is not showing that we had added in edit page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#795]
![image](https://user-images.githubusercontent.com/79301742/112289027-ed1bf880-8cb3-11eb-9c98-e92470512a7d.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done
![image](https://user-images.githubusercontent.com/67137586/113919319-1767cd00-9801-11eb-90f4-68e17e07a781.png)

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115112564-ba5bdc00-9fa3-11eb-956a-222f0c5a2f2c.png)


DONE
