### ISSUE TITLE
Driver :- If CDL number and license number is not same then error should occur

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#803]
If country state is not same in document details and license tab then also error should occur 
error should occur over the birth date . when we select the date then error occur coz less than 18 years old

**Comment by FH-sandeepkaur1** [comment]
If country state is not same in document details and license tab then also error should occur

**for the above point -** the documents that we are adding is multiple. so we cannot restrict the license country with the selected document country

**Comment by rashmi0301** [comment]
error should occur over the birth date ( and country also ) . when we select the date then error occur coz less than 18 years old  ( should be in driver model as well and document issue date  ) -- pending 
Applicable  for documents fields for all

**Comment by rashmi0301** [comment]
For Birth certificate Documents we only need canada, usa & mexico and their provinces

**Comment by rashmi0301** [comment]
@Daljit-fleetHawks 

CDL  document is in document type dropdown and in license section  but in both countries are different  . plz confirm can we keep as it is. and please discuss the other document in document type field

**Comment by rashmi0301** [comment]
will close after cdl is removed from list

**Comment by rashmi0301** [comment]
CDL is removed from the list
