### ISSUE TITLE
Login page :- If i am already logged in so when i open the dev / cloud app then firstly put the username and then password then click on submit button then we should redirect to the entire dashboard . 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#805]
![image](https://user-images.githubusercontent.com/79301742/117436093-6ded2780-aee3-11eb-8477-35b278493c77.png)

**Comment by FH-sandeepkaur1** [comment]
can you please provide a screenshot/video regarding this issue @rashmi0301

**Comment by rashmi0301** [comment]
This error occurs sometime . 
when we click on devapp link then directly dashboard screen is open.

**Comment by rashmi0301** [comment]
any update

**Comment by robinhawks** [comment]
@rashmi0301 resolve the issue

**Comment by robinhawks** [comment]
@rashmi0301 any update ?

**Comment by rashmi0301** [comment]
@robinhawks this is the technical issue dev can handle this

**Comment by rashmi0301** [comment]
Done now when we already login then login screen  should not appear 

then direct map dashboard is appear
