### ISSUE TITLE
When the login screen is appear then navigation menu should not appear 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#806]

**Comment by rashmi0301** [comment]
any update ?
this is still occur

**Comment by rashmi0301** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/79301742/117536965-f2f34200-afb2-11eb-89af-d6d2a537ae67.png)

this issue still occur but occur sometimes . 
this is the technical issue so developer can do this .

**Comment by AmitojSingh1** [comment]
Duplicate of #588
