### ISSUE TITLE
Service log :- In select task field some spell errors are there and some spells are cut off 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#810]
![image](https://user-images.githubusercontent.com/79301742/112432818-69234880-8d67-11eb-8c1e-ef5de4424916.png)
![image](https://user-images.githubusercontent.com/79301742/112432827-6c1e3900-8d67-11eb-952b-3de9bd9ff24e.png)
![image](https://user-images.githubusercontent.com/79301742/112432839-6f192980-8d67-11eb-97b3-e0b1b0ada97a.png)
![image](https://user-images.githubusercontent.com/79301742/112432846-70e2ed00-8d67-11eb-907f-0ccd8de54da1.png)

etc . please check all

**Comment by FH-sandeepkaur1** [comment]
@fleetui please check

**Comment by rashmi0301** [comment]
any update @fleetui

**Comment by rashmi0301** [comment]
any update ?

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by Daljit-fleetHawks** [comment]
Please ask Kunal to clean service tasks records from database

**Comment by rashmi0301** [comment]
if the text is more now it breaks in two - three lines . 
![image](https://user-images.githubusercontent.com/79301742/120489194-4cf5e600-c36c-11eb-8522-70a92c5ffa0d.png)

DONE
