### ISSUE TITLE
Service log - if we add issue and inventory then data is not properly showing in list page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#812]

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/112760434-c90a3100-8fab-11eb-9b49-edbe637abfe0.png)

2. issue is not appear on same screen of service log that we add through "plus icon "

**Comment by rashmi0301** [comment]
Now we need vehicle name and asset name should be autogenerated when we hit over the add issue button ( on service log add form ) and date should be autogenerated

**Comment by rashmi0301** [comment]
If we are adding issue through this popup then on issue module assigned by and reported to data is not showing . 
assigned to options are wrong showing

**Comment by rashmi0301** [comment]
DONE

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1  this issue happens again . 

scenario is that :- 

i am adding the new issue on service log add page but when i go to issue tab to see that particular issue then assigned to and reported by data is not appear .. 
and i m adding these while creating a new issue through service log ( add new issue popup ) 

![image](https://user-images.githubusercontent.com/79301742/117182466-3a978500-ad8b-11eb-93d2-fdf1e291b5bf.png)

**Comment by Daljit-fleetHawks** [comment]
Done @rashmi0301

**Comment by rashmi0301** [comment]
DONE

**Comment by robinhawks** [comment]
> @FH-sandeepkaur1 this issue happens again .
> 
> scenario is that :-
> 
> i am adding the new issue on service log add page but when i go to issue tab to see that particular issue then assigned to and reported by data is not appear ..
> and i m adding these while creating a new issue through service log ( add new issue popup )
> 
> ![image](https://user-images.githubusercontent.com/79301742/117182466-3a978500-ad8b-11eb-93d2-fdf1e291b5bf.png)

Checked and working !
