### ISSUE TITLE
Service log  :- vendor location Is blank , Discount taxes where it comes from

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#814]
![image](https://user-images.githubusercontent.com/79301742/112439804-907e1380-8d6f-11eb-868b-3d81e3f51990.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 This page needs to be re-design.

**Comment by rashmi0301** [comment]
OKAY

**Comment by rashmi0301** [comment]
@fleetui  please update when page is ready

**Comment by rashmi0301** [comment]
http://design.fleethawks.com/dashboard/service-log-details.php 

new page is in design link

**Comment by rashmi0301** [comment]
new design is done and checked
