### ISSUE TITLE
Service log :- Here should be Vehicle / Asset 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#815]
![image](https://user-images.githubusercontent.com/79301742/112450184-23bc4680-8d7a-11eb-9249-2e5927b2d239.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
DONE 

![image](https://user-images.githubusercontent.com/79301742/112613626-50d62b00-8e46-11eb-960b-7fc452ab6356.png)
