### ISSUE TITLE
order :- Charges data and reference text is not showing as per the add form 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#818]
![image](https://user-images.githubusercontent.com/79301742/112461579-10af7380-8d86-11eb-8417-cce0d64976bd.png)
![image](https://user-images.githubusercontent.com/79301742/112461609-19a04500-8d86-11eb-9c89-23668418718c.png)

**Comment by rashmi0301** [comment]
Including the charges .. states with taxes are not showing 
@fleetui please  look into this  where should we add these fields on order detail page ..

**Comment by FH-sandeepkaur1** [comment]
remarks is not there in design. rest you can check @rashmi0301

**Comment by rashmi0301** [comment]
Points are mentioned in orders task
