### ISSUE TITLE
Trips :- Remove comma 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#820]
![image](https://user-images.githubusercontent.com/79301742/112471170-908f0b00-8d91-11eb-8a33-df1b137d75a6.png)

date should be in single line 
remove comma from asset also

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/112833529-b47d7580-904b-11eb-82aa-f9ce175b6fa9.png)
1. here should be the trip# 
2. Remove s from asset

**Comment by FH-sandeepkaur1** [comment]
this point is done. Please review on dev-app @rashmi0301

**Comment by rashmi0301** [comment]
done
