### ISSUE TITLE
Trips :- I had selected the another order number but why this shows . is it static ?

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#821]
![image](https://user-images.githubusercontent.com/79301742/112471296-b7e5d800-8d91-11eb-8484-8f7290292adc.png)

**Comment by FH-sandeepkaur1** [comment]
this point is done. Please review on dev-app @rashmi0301

**Comment by FH-sandeepkaur1** [comment]
design for orders in detail page is changed. I will update you once it is done @rashmi0301

**Comment by rashmi0301** [comment]
okay

**Comment by rashmi0301** [comment]
done
