### ISSUE TITLE
Trips :- when edit the trip then  what type of miles are showing ?

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#822]
![image](https://user-images.githubusercontent.com/79301742/112471669-2f1b6c00-8d92-11eb-99d3-3a0254e2f075.png)

**Comment by FH-sandeepkaur1** [comment]
These miles are actual ones that are from orders which are selected.
The second miles are from pcmiler. It is according to the plan created
