### ISSUE TITLE
Driver :- This type of data should not proceed 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#827]
![image](https://user-images.githubusercontent.com/79301742/112589199-b9151480-8e26-11eb-80ff-e19620e7d539.png)

same for username

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/112747481-b4597900-8f6a-11eb-9d73-85396a465b13.png)


check this type of data for overall fields

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
we have to put the validations for all fields as per the discussion with @Hardeep8587 ....

**Comment by rashmi0301** [comment]
validation task is already created
