### ISSUE TITLE
Driver :- owner operator plus icon

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#829]
kindly check the states city . These should be valid  states . 

@fleetui  please increase the size of the boxes so that text should not cut off 

![image](https://user-images.githubusercontent.com/79301742/112614693-8d565680-8e47-11eb-90be-0d269a322959.png)

**Comment by rashmi0301** [comment]
Now we are working on states and cities for actual data . so we will add actual data for this . 
States are completed and Cities are in progress .

**Comment by rashmi0301** [comment]
cities and states data is completed

**Comment by rashmi0301** [comment]
@fleetui pankaj bhaji please fix the alignment spacing issue s

**Comment by pankaj-fleethawks** [comment]
![image](https://user-images.githubusercontent.com/63699936/115933789-45116f00-a4ad-11eb-91d3-523e699bbc18.png)

now done this point, now up to 19 character show in state and city

**Comment by rashmi0301** [comment]
done owner operator
