### ISSUE TITLE
Vehicle :- model plus icon of service program 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#833]
![image](https://user-images.githubusercontent.com/79301742/112624158-42424080-8e53-11eb-830b-53541ddceebf.png)

plus icon is not working 
data is not showing in dropdown

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/113551991-20934700-9613-11eb-892c-38124c55253c.png)

plus icon is not showing

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 We are not showing plus icons in modal

**Comment by rashmi0301** [comment]
okay
