### ISSUE TITLE
Driver detail page :- Here should be issued State and issued Country instead of Issued region 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#835]
![image](https://user-images.githubusercontent.com/79301742/112753673-6f930980-8f8d-11eb-8015-67f22a33582a.png)

**Comment by rashmi0301** [comment]
email styling should be same that what we had entered on add form . i had entered "test@gmail.com" but on detail view page first word capital is appear . As you can see below screenshot 
![image](https://user-images.githubusercontent.com/79301742/112753742-c7ca0b80-8f8d-11eb-8a5f-25fb6de0e810.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
This is done
