### ISSUE TITLE
Asset :- Model data is not showing in add form 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#836]
![image](https://user-images.githubusercontent.com/79301742/112755777-192ac880-8f97-11eb-90e4-45ff1ffd2152.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
Done

**Comment by rashmi0301** [comment]
http://devapp.fleethawks.com/#/fleet/assets/add
