### ISSUE TITLE
Asset :- Proper data show in detail view page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#837]
1. put License Province instead of "License state 
2.  License country is missing 
3. Annual safety date is missing 
4. Group is missing 
5. Start date is missing 
6. Asset status is missing 
7. Aci id and ACE id is missing 
8. put Asset Name/ Number instead of asset name /ID

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Done

**Comment by rashmi0301** [comment]
This is DONE 
http://devapp.fleethawks.com/#/fleet/assets/add
