### ISSUE TITLE
Inventory :- Field size should be large 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#838]
![image](https://user-images.githubusercontent.com/79301742/112756953-58a7e380-8f9c-11eb-826e-9f8cc0f41795.png)

**Comment by rashmi0301** [comment]
any update @fleetui

**Comment by pankaj-fleethawks** [comment]
Done this point @rashmi0301 , check it now

**Comment by rashmi0301** [comment]
DONE
