### ISSUE TITLE
Trips :- miles are not properly working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#840]
![image](https://user-images.githubusercontent.com/79301742/112834721-2d310180-904d-11eb-9a46-0b06bccac4e9.png)

1. if i delete the extra stops then miles are not changed . check above screenshot

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/112835278-e8f23100-904d-11eb-9ac4-b3d252d9336e.png)
![image](https://user-images.githubusercontent.com/79301742/112835443-1f2fb080-904e-11eb-8fee-fbfca4048b50.png)

**Comment by AmitojSingh1** [comment]
@FH-sandeepkaur1 Is it resolved?

**Comment by FH-sandeepkaur1** [comment]
yes it is done

**Comment by rashmi0301** [comment]
![Screenshot (49)](https://user-images.githubusercontent.com/79301742/114163518-e80fa800-9947-11eb-89df-6f5aa61415cf.png)


if im deleting the trip then miles are not changed

**Comment by rashmi0301** [comment]
working ..
now if we delete the miles then calculation miles are okay
