### ISSUE TITLE
Trip :- vehicle , driver , asset , carrier data is not showing over the list view table 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#841]
![image](https://user-images.githubusercontent.com/79301742/112835872-b563d680-904e-11eb-9989-7dc890e872db.png)

**Comment by rashmi0301** [comment]
Not showing 
any update @FH-sandeepkaur1

**Comment by FH-sandeepkaur1** [comment]
These will only be there if they are selected while planning trip. else they will be empty

**Comment by rashmi0301** [comment]
Vehicle , driver , asset is not showing while we adding  & when  we create trip ... is it correct 
But carrier is also showing when i create the trip and selected the carrier ?

and yes when creating the planning trip then vehicle , asset , driver is showing .

**Comment by rashmi0301** [comment]
DONE
