### ISSUE TITLE
Trips :- Items are missing in detail view page , some items are static , some occur error

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#842]
1. Reefer temperature is missing 
2. Notifications are missing
3. miles are missing 
4. start date is missing 
5. permanent route is missing 
6. send to manifest button --- error occur 
7. Fuel expenses , other expenses -- error occur 
8.  fuel expenses , trip information , driver activity , planned actual trips , order information --- is it static
![Screenshot (13)](https://user-images.githubusercontent.com/79301742/112836753-d5e06080-904f-11eb-8650-22ff911bb946.png)

9. put order# instead of order no.  -- list view page 
10. Put select order# instead of select order number -- add form 
11.  remove hyphen between the pickup . and put drop off instead of drop -- list view 
12.  check below screenshot . These should be in serial order as per the add form . and co-driver is missing in list view table . Remove the s from assets . in add form , list view and in popup also . 
![image](https://user-images.githubusercontent.com/79301742/114377915-cceda400-9ba4-11eb-84a5-7f54dab98696.png)

13. Put s with the action 
14. put drop off instead of drop -- add from 
15.  check below screenshot :- here should be pickup location , drop off location 

![image](https://user-images.githubusercontent.com/79301742/114378457-59986200-9ba5-11eb-8508-f84e44c51a41.png)

16. Remove this checkbox . check below screenshot 
![image](https://user-images.githubusercontent.com/79301742/114378538-72087c80-9ba5-11eb-8798-47cde9688601.png)

17. put drop off location instead of delivery  -- detail page as well in trip route section 
18.  check below screenshot in detail page -- these should be in serial order in add form , detail , list view . and put asset instead of trailer .
![image](https://user-images.githubusercontent.com/79301742/114380282-8d748700-9ba7-11eb-88fd-940cbb3e232f.png)

19. Remove create trip button from detail page

**Comment by pankaj-fleethawks** [comment]
Notification now in detail page, check @rashmi0301 
http://design.fleethawks.com/dashboard/trip-detail.php

**Comment by rashmi0301** [comment]
Notification now in detail page,
http://design.fleethawks.com/dashboard/trip-detail.php

**Comment by rashmi0301** [comment]
miles are missing -- DONE 


Rest all Pending

**Comment by FH-sandeepkaur1** [comment]
@fleetui  please do the required changes and let me know

**Comment by rashmi0301** [comment]
1. Reefer temperature is missing -- done 
2. Notifications are missing -- done 
3.  start date is missing --- done 
4.  permanent route is missing -- done 
5.  send to manifest button --- error occur
6.  Fuel expenses , other expenses -- done
7. fuel expenses , trip information , driver activity , planned actual trips , order information --- is it static , coming eld 
8.  put order# instead of order no. -- list view page -- done 
9.  Put select order# instead of select order number -- add form -- done 
10.  remove hyphen between the pickup . and put drop off instead of drop -- list view--- done
11.  check below screenshot . These should be in serial order as per the add form . and co-driver is missing in list view table . Remove the s from assets . in add form , list view and in popup also . --- not done 
12. Put s with the action -- done 
13.  put drop off instead of drop -- add from -- done 
14.  here should be pickup location , drop off location -- done 
15.  Remove this checkbox . check below screenshot -- not done 
16.  put drop off location instead of delivery -- detail page as well in trip route section -- done
17.  check below screenshot in detail page -- these should be in serial order in add form , detail , list view . and put asset instead of trailer . -- not done 
18. Remove create trip button from detail page -- done 


please cheeck the not done points

**Comment by rashmi0301** [comment]
done
