### ISSUE TITLE
Order :- phone number ,  address is not showing 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#844]
![image](https://user-images.githubusercontent.com/79301742/112872361-261de980-9075-11eb-82eb-32995e6d8cbb.png)

**Comment by AmitojSingh1** [comment]
This is fixed: the address field is empty so that's why it's showing empty. 
@gauravfleethawks 
![image](https://user-images.githubusercontent.com/72762922/113936558-29238300-97b5-11eb-9daf-2df30fd6a775.png)

**Comment by rashmi0301** [comment]
Not showing @AmitojSingh1 
![image](https://user-images.githubusercontent.com/79301742/114029505-32851c00-9897-11eb-91f0-1473aab3b8c6.png)

**Comment by rashmi0301** [comment]
DONE
