### ISSUE TITLE
orders :- these should consignee and consignor 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#845]
![image](https://user-images.githubusercontent.com/79301742/112873310-50bc7200-9076-11eb-9efd-d6448362d7de.png)

**Comment by AmitojSingh1** [comment]
I think @rashmi0301 it's fixed please test and closed

**Comment by rashmi0301** [comment]
No @AmitojSingh1 its not done 

![image](https://user-images.githubusercontent.com/79301742/114022463-6ceabb00-988f-11eb-9687-addca8b011ce.png)

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/114820169-36a3c300-9ddc-11eb-863e-f500cc067d1d.png)

still occur

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115227547-37b35800-a12e-11eb-9eab-8108ce755eb9.png)


still occurs

**Comment by pankaj-fleethawks** [comment]
yes rashmi..this issue was on, now its done so check @rashmi0301 now

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115512601-ca273900-a29f-11eb-95d0-07aefdeb2eb3.png)


done
