### ISSUE TITLE
Order:- Items are not showing properly over the detail view page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#846]
1. Address is not showing
2. wrong reference data is showing
3. Charges are not showing properly
4. Advance received data is showing wrong
5. Put Del instead of Pu -- DONE 
6. Fax data is wrong ( static )
7. PU# is not showing - DETAIL PAGE 
8.  check below screenshot this type of data where it comes from ?
![image](https://user-images.githubusercontent.com/79301742/112875110-9c701b00-9078-11eb-9269-5a828cc7752b.png)
9. attachment is not showing . On clicking the Receipt number it redirect to homepage . check below screenshot 
![image](https://user-images.githubusercontent.com/79301742/113703705-d6849100-96f8-11eb-9d3a-aff59d50d076.png)

10. Put consignee and consignor instead of shipper and receiver 
 
![image](https://user-images.githubusercontent.com/79301742/114365289-fa802080-9b97-11eb-8ef9-d78b5906c4cd.png)

11. if im adding more commodities then which commodity is showing here . check above screenshot 
12. if i am on the editing page then customer details are not showing 
13. put province instead of state -- DONE
14.  put asset instead of trailer on add form and detail page . -- DONE
15.  Accessorial amount option , deduction  option that we had selected are not showing on detail page 
16. Remarks field is not showing on detail page . 
17.  states that we had selected is not showing on detail page . 

18. if we are miles are from google , PC and if it is manual where we show that these miles from google , pc , manual  ?
19. wrong customer name is showing 
20. put order# instead of Order and put order#    -- list view page / add form -- DONE
21. Put drop off instead of drop  and put pickup location and drop off location -- list view page -- DONE 
22.  if i had saved the shipper data then receivers data is also removed . tried 2 times 
23. on add form -- when pickup time and delivery time is same then error should occur 
24. validation should occur when invalid data is there 
![image](https://user-images.githubusercontent.com/79301742/115355564-6ab22600-a1d8-11eb-8b89-5dea8c1c9119.png)

**Comment by rashmi0301** [comment]
any update @Daljit-fleetHawks @gauravfleethawks

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 any update

**Comment by rashmi0301** [comment]
1. Address is not showing -- DONE 
2.  wrong reference data is showing -- DONE 
3.  Charges are not showing properly -- DONE 
4. Advance received data is showing wrong --- REMOVED 
5. Put Del instead of Pu -- DONE
6. Fax data is wrong ( static )  -- DONE 
7. PU# is not showing - DETAIL PAGE  -- DONE 
8.  Put consignee and consignor instead of shipper and receiver -- DONE 
9.  if im adding more commodities then which commodity is showing here . -- SINGLE WILL SHOW 
10.  if i am on the editing page then customer details are not showing -- NOT DONE 
11.  put asset instead of trailer on add form and detail page . -- DONE 
12.  Accessorial amount option , deduction option that we had selected are not showing on detail page -- DONE 
13.  if we are miles are from google , PC and if it is manual where we show that these miles from google , pc , manual ? -- DONE
14.  wrong customer name is showing -- DONE ( company name will show )
15.  put order# instead of Order and put order# -- list view page / add form -- DONE
16. Put drop off instead of drop and put pickup location and drop off location -- list view page -- DONE

**Comment by rashmi0301** [comment]
PENDING 

1. validation should occur when invalid data is there 
2. if i had saved the shipper data then receivers data is also removed . tried 2 times
3. Remarks field is not showing on detail page .
4. states that we had selected is not showing on detail page .
5. while editing the customer details are not showing 

REMOVE THIS 
![image](https://user-images.githubusercontent.com/79301742/115705189-e0a9bf00-a389-11eb-96b4-6b3768693490.png)

6. while editing and while creating -- miles are not properly working 
7. status is not working properly

**Comment by FH-sandeepkaur1** [comment]
Please review all and the followings

- pc miler issue
- removed mandatory from asome fields ad discssed with param veera
- commodity, quantity, weight will be same as shipper but user can also edit them

**Comment by rashmi0301** [comment]
PENDING 

1. Now if we hit the edit icon of the shipment 2 details then same details are also opened in shipment 1 . 
2. Remove the google miles as per the discussion 
3. Remove the Remarks field as per the discussion 
4. when we hit over the add more button then shipment 1 box should not be opened 
5. calculations are wrong in detail page while ticked the zero rated . please go through it with provinces also 
6.  Now consignor and consignee is not working while we are adding through plus icon 
7. When we are on editing page then attachment is not showing  
8. total amount on list view -- remove 00 at last

**Comment by rashmi0301** [comment]
DONE 

pc miler issue
removed mandatory from a some fields ad discussed with param veera
commodity, quantity, weight will be same as shipper but user can also edit them
if i had saved the shipper data then receivers data is also removed . tried 2 times
status is not working properly

**Comment by rashmi0301** [comment]
Remove the google miles as per the discussion  -- DONE 
Remove the Remarks field as per the discussion --  DONE 
total amount on list view -- remove 00 at last -- DONE 
calculations are wrong in detail page while ticked the zero rated . please go through it with provinces also -- DONE
