### ISSUE TITLE
Sign Up is not working 

### ISSUE THREAD

**Issue by AmitojSingh1** [Fleet-Hawks-Inc/fh-cloud-app#847]
I am getting validation errors while signing up. 
![image](https://user-images.githubusercontent.com/72762922/112897912-6f822f00-909d-11eb-85b1-fbefca713d51.png)

**Comment by rashmi0301** [comment]
@AmitojSingh1  this issue is already created

**Comment by Hardeep8587** [comment]
@AmitojSingh1  it needs discussion

**Comment by AmitojSingh1** [comment]
already created at #656
