### ISSUE TITLE
Cross border :- put asset instead of Trailer

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#849]
![image](https://user-images.githubusercontent.com/79301742/112945124-7cf8f100-9151-11eb-8b93-1bf6c3de796e.png)

Remove comma in shipment , trailer , consignor and consignee

**Comment by AmitojSingh1** [comment]
Fixed in PR #850

**Comment by rashmi0301** [comment]
DONE
