### ISSUE TITLE
Cross border:- when we edit the detail then blank  IIT field  is appear 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#852]
![image](https://user-images.githubusercontent.com/79301742/114134032-a1f51d00-9924-11eb-9a09-640a2bf36efc.png)

raw data in co - driver 
Trip number is blank

**Comment by Hardeep8587** [comment]
![ACE](https://user-images.githubusercontent.com/63697698/113099402-864c9100-9217-11eb-9a87-69a2b3af78f4.png)
Adding IIT for each vehicle and asset..

**Comment by Hardeep8587** [comment]
![IIT](https://user-images.githubusercontent.com/63697698/113099608-d62b5800-9217-11eb-84d4-86fb48111776.png)
While creating object , it's included just once!

**Comment by rashmi0301** [comment]
any update @AmitojSingh1

**Comment by rashmi0301** [comment]
Still not appear the IIT status , fast card when we are editing page -- ACE

**Comment by Hardeep8587** [comment]
@rashmi0301 please check now

**Comment by Hardeep8587** [comment]
please close this task even if it's done, just comment, we have opened this task for other backend reason too

**Comment by rashmi0301** [comment]
done
