### ISSUE TITLE
Cross Border :- error should occur when  we are selecting the same driver name and same co driver name 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#855]
![image](https://user-images.githubusercontent.com/79301742/112964131-aae83080-9165-11eb-9e25-02005de8d2f4.png)

**Comment by AmitojSingh1** [comment]
@rashmi0301 please test and close

**Comment by rashmi0301** [comment]
Now its fine . Checked on devapp . 
same driver is not showing on co driver field
