### ISSUE TITLE
Trip :- data is not showing like order number miles when we are on edit page

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#856]
![image](https://user-images.githubusercontent.com/79301742/112972810-4bdae980-916e-11eb-9155-4b7f8afe10b6.png)

**Comment by FH-sandeepkaur1** [comment]
It might be due to slow internet. It is working fine on dev-app

**Comment by rashmi0301** [comment]
yes now its fine . here is the screenshot of editing page  and order/miles are showing 

![image](https://user-images.githubusercontent.com/79301742/114021111-f13c3e80-988d-11eb-96d6-7324d04b122e.png)
