### ISSUE TITLE
planner :- Vehicles are not showing

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#858]
![image](https://user-images.githubusercontent.com/79301742/112986610-53ef5500-917f-11eb-9075-d77665c2cbcf.png)

**Comment by FH-sandeepkaur1** [comment]
this point is done. Please review on dev-app @rashmi0301

**Comment by rashmi0301** [comment]
Done on DEV 

![image](https://user-images.githubusercontent.com/79301742/114020955-c5b95400-988d-11eb-929e-d0cf60229014.png)
