### ISSUE TITLE
Issue :- Date should be autogenerated 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#862]

**Comment by AmitojSingh1** [comment]
@rashmi0301 Where on the issues page it should be autogenerated?

**Comment by rashmi0301** [comment]
@Hardeep8587 is working on that 
![Screenshot (43)](https://user-images.githubusercontent.com/79301742/114028617-4f6d1f80-9896-11eb-8dd0-4706b8ac89a2.png)

**Comment by rashmi0301** [comment]
done
