### ISSUE TITLE
Service log :- On issue popup Reported date and vehicle name should be automatic

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#864]
![image](https://user-images.githubusercontent.com/79301742/113121125-f109c680-922f-11eb-8343-b14a103a1978.png)

**Comment by rashmi0301** [comment]
any update @Hardeep8587

**Comment by robinhawks** [comment]
@Hardeep8587 it is pending from last one month, there was no update from you on this
do let know if you have any hurdle

**Comment by Hardeep8587** [comment]
@robinhawks , didn't get a chance to look into it, I will look into it, once I finish asset part, I will resolve issues

**Comment by Daljit-fleetHawks** [comment]
Done @rashmi0301

**Comment by rashmi0301** [comment]
done

**Comment by robinhawks** [comment]
Working and checked !
