### ISSUE TITLE
Service log :- need to redesign the detail page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#865]
![image](https://user-images.githubusercontent.com/79301742/113121125-f109c680-922f-11eb-8343-b14a103a1978.png)

**Comment by AmitojSingh1** [comment]
@rashmi0301 I think it's fixed please test and close the issue

**Comment by rashmi0301** [comment]
http://design.fleethawks.com/dashboard/service-log-details.php
