### ISSUE TITLE
Vehicle:- Full name of vehicle type should appear on list view page and detail view page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#869]
![image](https://user-images.githubusercontent.com/79301742/113383138-e458b000-93a0-11eb-81b2-5249737a3d0f.png)

**Comment by rashmi0301** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/79301742/113565045-fdbf5d80-9627-11eb-9483-48e7403f056b.png)
Not done on detail view page

**Comment by AmitojSingh1** [comment]
@rashmi it's fixed on my end. Please test again. Lemme know if it's not fixed

**Comment by rashmi0301** [comment]
DONE on devapp 

![image](https://user-images.githubusercontent.com/79301742/114020704-80952200-988d-11eb-8d6e-72b0122db7e3.png)
