### ISSUE TITLE
Driver :- Options under the document type field 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#872]
![image](https://user-images.githubusercontent.com/79301742/113394142-59ce7b80-93b5-11eb-8d65-226d89e47fce.png)

@Daljit-fleetHawks  Kindly discuss which fields we need to keep

**Comment by AmitojSingh1** [comment]
@Daljit-fleetHawks Is it discussed yet?

**Comment by rashmi0301** [comment]
ANY UPDATE @Daljit-fleetHawks

**Comment by Daljit-fleetHawks** [comment]
> ANY UPDATE @Daljit-fleetHawks

@rashmi0301 @AmitojSingh1 It has been discussed and we are keeping all the options as of now.

**Comment by rashmi0301** [comment]
okay @Daljit-fleetHawks
