### ISSUE TITLE
Pagination is not working when delete the entry 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#877]
![image](https://user-images.githubusercontent.com/79301742/113474756-92428800-948f-11eb-980d-6690867cfe77.png)

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 any update

**Comment by FH-sandeepkaur1** [comment]
please check

**Comment by rashmi0301** [comment]
Now  when we delete the entry then pagination is working
