### ISSUE TITLE
Driver :- Validation message should occur over this field 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#880]
![image](https://user-images.githubusercontent.com/79301742/113548862-f1c6a200-960d-11eb-94cb-6a60617e7f71.png)

**Comment by Daljit-fleetHawks** [comment]
@rashmi0301 Its already coming
Please see
![image](https://user-images.githubusercontent.com/67137586/113917783-43824e80-97ff-11eb-97fc-f1f0cecf12dc.png)

**Comment by rashmi0301** [comment]
still this is not appear at my end @Daljit-fleetHawks

**Comment by rashmi0301** [comment]
new driver page is in progress
