### ISSUE TITLE
Vehicle :- data is not showing as expected 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#885]
![image](https://user-images.githubusercontent.com/79301742/113564281-be444180-9626-11eb-96b5-11b826d938b6.png)

**Comment by rashmi0301** [comment]
we need full name here also 
Remove View all buttons from this page 

![image](https://user-images.githubusercontent.com/79301742/113564429-006d8300-9627-11eb-9eab-8f902e517c54.png)

**Comment by rashmi0301** [comment]
Service program and annual safety date is not showing 

![Screenshot (25)](https://user-images.githubusercontent.com/79301742/113566519-73c4c400-962a-11eb-9b9f-9e939200f807.png)


2. Units are not appear on tare weight , gross weight over the detail view page 

3. Reminder data is not showing as expected . check below both screenshots . 

![image](https://user-images.githubusercontent.com/79301742/113566714-dcac3c00-962a-11eb-87bd-2ba905ce1dca.png)
![Screenshot (26)](https://user-images.githubusercontent.com/79301742/113566725-e0d85980-962a-11eb-9847-4ab134aed156.png)

4. make the units of height / ground clearance should same as per asset
5. On list view page correct data is not showing . Eg. ownership , assigned driver , group ... Wrong data is showing . please check detail view page and list view . 

6. If i opened the editing page then the value of the owner operator , add document  is not showing .

7. In add form :- Put province instead of state

**Comment by rashmi0301** [comment]
Pending 

1. service program is not showing on list view 
2. Start date not showing -- on list view 
3. Insurance amount with currency is not showing -- list view 
4. Fuel unit and primary meter data ( static)  -- list view 
5. If i opened the editing page then the value of the owner operator , add document is not showing .
6. Service program and annual safety date , inspection form , Enable IFTA Reporting is not showing - detail page 
7.  Units are not appear on tare weight , gross weight over the detail view page
8.  If we selected the ownership then owner operator name is not showing -- detail view 
9. on add page -- please add sliders in a photo section / images are not showing properly on detail page 
10. On giving the down payment in usd after that it will give the error on the monthly payment field if user select on cad currrency ( same for purchase) . and on loan tab :- if our calculations are wrong then error should occur 
11.  Reminder Every properly is not showing -- detail page 
![image](https://user-images.githubusercontent.com/79301742/115832503-9891a780-a430-11eb-82fb-6809fe13d3e3.png)
![image](https://user-images.githubusercontent.com/79301742/115832912-12299580-a431-11eb-9dcd-39b51185d012.png)




![image](https://user-images.githubusercontent.com/79301742/115222167-12235000-a128-11eb-9958-062d487432d1.png)

check above screenshot data is not showing 

12. On clicking the documents 1 ,2,3  please add a link over there so that when we click over there then document should open from here also . 
13.  i am adding  only 2 documents but 3 are showing ? please figure it out 
14. On clicking the view submission , nothing happens . and inspections forms are not showing .
![image](https://user-images.githubusercontent.com/79301742/115834927-5fa70200-a433-11eb-9787-c062e0e5cf96.png)

15. inactive, sold , out of service -- searching is not working 
16. Under the details :- if the premium amount is in Canadian and insurance amount is in USD then error occur or not ?
17.  vehicle models --- inspection field is missing

**Comment by FH-sandeepkaur1** [comment]
Please check the followings:
1. service program is not showing on list view -- done
2. Start date not showing -- on list view -- done
3. Insurance amount with currency is not showing -- list view -- done
4. Fuel unit and primary meter data ( static) -- list view -- It is removed for now as discussion with gaurav
5. If i opened the editing page then the value of the owner operator , add document is not showing . -- done
6. Service program and annual safety date , inspection form , Enable IFTA Reporting is not showing - detail page -- done
7. Units are not appear on tare weight , gross weight over the detail view page -- done
8. If we selected the ownership then owner operator name is not showing -- detail view  -- done
9. On clicking the documents 1 ,2,3 please add a link over there so that when we click over there then document should open from here also . -- done
10. On clicking the view submission , nothing happens . and inspections forms are not showing . -- done

**Comment by rashmi0301** [comment]
1. service program is not showing on list view -- done
2. Start date not showing -- on list view -- done
3. Insurance amount with currency is not showing -- list view -- done
4. Fuel unit and primary meter data ( static) -- list view -- It is removed for now as discussion with gaurav
5. If i opened the editing page then the value of the owner operator , add document is not showing . -- done
7. Units are not appear on tare weight , gross weight over the detail view page -- done
8. If we selected the ownership then owner operator name is not showing -- detail view  -- done
9. On clicking the documents 1 ,2,3 please add a link over there so that when we click over there then document should open from here also . -- done
10. On clicking the view submission , nothing happens . and inspections forms are not showing . -- done

6. Service program and annual safety date , inspection form , Enable IFTA Reporting is not showing - detail page -- NOT DONE

**Comment by rashmi0301** [comment]
1. on add page -- please add sliders in a photo section / images are not showing properly on detail page
2. On giving the down payment in usd after that it will give the error on the monthly payment field if user select on cad currrency ( same for purchase) . and on loan tab :- if our calculations are wrong then error should occur
3. Service program and annual safety date , inspection form , Enable IFTA Reporting is not showing - detail page -- NOT DONE
4. inactive, sold , out of service -- searching is not working
5. Under the details :- if the premium amount is in Canadian and insurance amount is in USD then error occur or not ?

**Comment by rashmi0301** [comment]
for new vehicle design i will create new issue
