### ISSUE TITLE
Service reminder :-  NAN miles are showing 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#891]
![image](https://user-images.githubusercontent.com/79301742/113668133-70374880-96cf-11eb-9517-69774685877f.png)

what is the calculation for this ?

1. Overdue , due soon status is not working properly 
2. Send notification on both list view / add form should work 
3. Nan miles calculations
4. On add form and editing page -- when we click on save and update button then subscribed user data is not appear . only cross is appear 
5. last completed date in service reminder . Where it comes from . If im not adding the service log .

**Comment by Hardeep8587** [comment]
@rashmi0301  please check on devapp, it's done

**Comment by rashmi0301** [comment]
On add form and editing page -- when we click on save and update button then subscribed user data is not appear . only cross is appear -- Not done still cross is showing . 
last completed date is when our service is completed 
2500 miles is the half of odometer miles that we had added in add form 
Overdue , due soon status is not working properly -- DONE 

Calculations are dummy

**Comment by rashmi0301** [comment]
On add form and editing page -- when we click on save and update button then subscribed user data is not appear . only cross is appear -- Not done still cross is showing . 

Currently driver is not working so im not able to check the mail

**Comment by rashmi0301** [comment]
DONE
