### ISSUE TITLE
Issue :- Search issue by name is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#893]
![Screenshot (27)](https://user-images.githubusercontent.com/79301742/113674804-3c145580-96d8-11eb-892c-711c10b02594.png)
![Screenshot (28)](https://user-images.githubusercontent.com/79301742/113674811-3dde1900-96d8-11eb-9045-c1850746a089.png)
![Screenshot (29)](https://user-images.githubusercontent.com/79301742/113674815-3e76af80-96d8-11eb-8a64-72ac653598f7.png)

**Comment by FH-sandeepkaur1** [comment]
this point is done @rashmi0301

**Comment by rashmi0301** [comment]
1. Searching is not working if i am putting full name in caps   , without selecting from suggestions . ( rather it is company name and carrier name ) -- then No data found is appear
--
2. if user had entered the first word  in caps and rest are small then searching should work
3. Without entering anything in search box then click on Search button. error should occur
4. Enter only special characters in search field and click on Search button. error should occur

**Comment by FH-sandeepkaur1** [comment]
For now no error messages will be there as mentioned in point 3 and 4 as discussed with @robinhawks . we will implement it later if  required.
Please check search scenarios 1 and 2 are working in whole fleet @rashmi0301

**Comment by rashmi0301** [comment]
Issue tab DONE
