### ISSUE TITLE
Service log :- If we are adding new part  then part name is not appear in dropdown 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#896]
![image](https://user-images.githubusercontent.com/79301742/113694304-3117f000-96ed-11eb-8278-5b0f5559c5e0.png)

**Comment by rashmi0301** [comment]
any update @Daljit-fleetHawks

**Comment by FH-sandeepkaur1** [comment]
If a new part is added then it will be listed under required inventory in inventory module.

**Comment by rashmi0301** [comment]
okay . 
now existing inventory will show . and new part is showing in inventory module
