### ISSUE TITLE
Service log :- Select a task is not working . Error occur 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#897]
![image](https://user-images.githubusercontent.com/79301742/113695202-3d507d00-96ee-11eb-8806-cbbb8bbc726d.png)

**Comment by rashmi0301** [comment]
NOT WORKING

**Comment by rashmi0301** [comment]
NOT WORKING 
CHECKED OVER A NEW RECORD

**Comment by FH-sandeepkaur1** [comment]
somehow code is not there. working on it again. I will update you soon

**Comment by rashmi0301** [comment]
Working now
