### ISSUE TITLE
Route :- Asset model is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#899]
![image](https://user-images.githubusercontent.com/79301742/113699395-22343c00-96f3-11eb-9eb4-f19439ac7f50.png)

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/114848755-a88c0480-9dfc-11eb-834d-4cad6854a1c1.png)

@AmitojSingh1 @FH-sandeepkaur1

**Comment by FH-sandeepkaur1** [comment]
It is the error of inspection form. @AmitojSingh1 is working on it

**Comment by rashmi0301** [comment]
working now

**Comment by rashmi0301** [comment]
plus icon is Not working 
Vehicle -- inspection field is missing

**Comment by rashmi0301** [comment]
working

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/118374873-f79b9580-b572-11eb-8401-4cc5ebb39b99.png)


not working

**Comment by FH-sandeepkaur1** [comment]
It is working. Please check

**Comment by rashmi0301** [comment]
working

**Comment by robinhawks** [comment]
@rashmi0301 Make sure its working and you need to attach the screenshot while closing as you said it was working !

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119203389-c413ac00-ba47-11eb-95a6-2ef6e7b097f9.png)

@robinhawks
