### ISSUE TITLE
planner :- Only confirmed Trips should show 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#902]
![image](https://user-images.githubusercontent.com/79301742/113706218-0bdeae00-96fc-11eb-882d-f0cc476a8c51.png)

**Comment by FH-sandeepkaur1** [comment]
On calendar all created trips will be there as discussed with @FHAdmin 
Confirmed thing is only for the sidebar in planner

**Comment by rashmi0301** [comment]
okay . so dispatched , confirmed all trips are appear on calendar 
confirmed trips are appear  on right side bar in planner 

Its done on dev app
