### ISSUE TITLE
Driver :-  Text change 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#921]
1. Put Fast card# instead of fast# in add from and same in detail page 
2. cross border tab details are showing under the  basic details  . so can you make them same as per the add form . add cross border and cross border details over there 
3. put Document# instead of document number in detail page 
4. put WCB# and health care#  instead of WCB and Health care 
5. Remove hos text in detail . if not then you can add HOS text in add form instead of cycle 

![image](https://user-images.githubusercontent.com/79301742/114144807-56963b00-9933-11eb-83cf-307650bbf8de.png)

put work phone and work email instead of email and phone 
 Remove hos text in detail . if not then you can add HOS text in add form instead of cycle 
put CDL number instead of CDL

**Comment by FH-sandeepkaur1** [comment]
@AmitojSingh1 are you working on it?

**Comment by rashmi0301** [comment]
cross border tab details are showing under the basic details . so can you make them same as per the add form . cross border details should shown under the cross border tab .

**Comment by rashmi0301** [comment]
new driver design is in progress
