### ISSUE TITLE
Documents :- DATE searching is not working properly 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#926]
![image](https://user-images.githubusercontent.com/79301742/114552850-a43bdc00-9c82-11eb-8907-b74b37fe9680.png)

**Comment by rashmi0301** [comment]
done

**Comment by rashmi0301** [comment]
Now again document searching is not working . checked over new record

**Comment by FH-sandeepkaur1** [comment]
Please check by adding new records

**Comment by rashmi0301** [comment]
in case sensitive this is not working

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119723174-03fcd980-be22-11eb-9f13-ad562792b292.png)

not working in case sensitive

**Comment by rashmi0301** [comment]
working in case sensitive
