### ISSUE TITLE
Document :-  needs to do some changes 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#927]
![Screenshot (52)](https://user-images.githubusercontent.com/79301742/114356645-81300000-9b8e-11eb-92bf-29f9d5da3047.png)
![Screenshot (53)](https://user-images.githubusercontent.com/79301742/114356651-82f9c380-9b8e-11eb-938b-a324f82a954b.png)

1. date is not showing 
2. put document type instead of type 
3.  Download button is not working 
4.  fix the alignment of the choose file field . and make the title black .
5. in same popup - in document type options here should be BOL# and POD#
6.  Remove download button from header
7. Buttons in popup should be cancel and save 
8. when i edit the form then created date is disappear 
9. when i again hit on add document to add another document then previous file is appear .

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/114356834-aa509080-9b8e-11eb-8c6d-38c7224c8499.png)

please correct the top text . it should be add document . 
can you  make this popup in center so that from all sides spacing should equal

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/114357105-f7346700-9b8e-11eb-8a72-54c35a1f426d.png)
 

put the red stars and optional with the title names

**Comment by rashmi0301** [comment]
1. put the red stars and optional with the title names -- DONE 
2. please correct the top text . it should be add document  --- DONE 
3.  put document type instead of type -- DONE 
4.  Download button is not working --- done 
5. in same popup - in document type options here should be BOL# and POD# -- DONE 
6. Remove download button from header -- DONE

**Comment by rashmi0301** [comment]
fix the alignment of the choose file field . and make the title black . -- PENDING 
Description field size needs large  -- PENDING 
Document type in list view :- # is not showing  -- PENDING 
when i again hit on add document to add another document then previous file is appear . -- PENDING

**Comment by FH-sandeepkaur1** [comment]
Description field size needs large -- PENDING = design issue    @fleetui

**Comment by rashmi0301** [comment]
Document type in list view :- # is not showing -- DONE
when i again hit on add document to add another document then previous file is appear . -- DONE

fix the alignment of the choose file field . and make the title black . -- PENDING
Description field size needs large -- PENDING

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115844404-69cdfe00-a43d-11eb-9b8a-c10bb8bfe5eb.png)

**Comment by pankaj-fleethawks** [comment]
> ![image](https://user-images.githubusercontent.com/79301742/114356834-aa509080-9b8e-11eb-8c6d-38c7224c8499.png)
> 
> please correct the top text . it should be add document .
> can you make this popup in center so that from all sides spacing should equal

this point has been done already

**Comment by pankaj-fleethawks** [comment]
> ![image](https://user-images.githubusercontent.com/79301742/114357105-f7346700-9b8e-11eb-8a72-54c35a1f426d.png)
> 
> put the red stars and optional with the title names

this point has been done already..

**Comment by pankaj-fleethawks** [comment]
> fix the alignment of the choose file field . and make the title black . -- PENDING
> Description field size needs large -- PENDING
> Document type in list view :- # is not showing -- PENDING
> when i again hit on add document to add another document then previous file is appear . -- PENDING

1st three points has been done.. @rashmi0301

**Comment by pankaj-fleethawks** [comment]
> Description field size needs large -- PENDING = design issue @fleetui

done this point @rashmi0301 ..

**Comment by pankaj-fleethawks** [comment]
> Document type in list view :- # is not showing -- DONE
> when i again hit on add document to add another document then previous file is appear . -- DONE
> 
> fix the alignment of the choose file field . and make the title black . -- PENDING
> Description field size needs large -- PENDING

done last two points @rashmi0301

**Comment by pankaj-fleethawks** [comment]
@rashmi0301 
document list view page point done on design link, where column height alignment not good due to large description....
http://design.fleethawks.com/dashboard/my-documents.php

now there is button, click on that to show all description
now developer need to implement this on dev link.. Thanks

**Comment by rashmi0301** [comment]
fix the alignment of the choose file field . and make the title black . -- DONE
Description field size needs large -- DONE

**Comment by rashmi0301** [comment]
> @rashmi0301
> document list view page point done on design link, where column height alignment not good due to large description....
> http://design.fleethawks.com/dashboard/my-documents.php
> 
> now there is button, click on that to show all description
> now developer need to implement this on dev link.. Thanks

@FH-sandeepkaur1  please follow this

**Comment by FH-sandeepkaur1** [comment]
sure I will implement it

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 now when i try to edit the form then created date is not appear 
![image](https://user-images.githubusercontent.com/79301742/116194181-1d8d0180-a74e-11eb-9fba-12cb38a505ce.png)

**Comment by rashmi0301** [comment]
> @FH-sandeepkaur1 now when i try to edit the form then created date is not appear
> ![image](https://user-images.githubusercontent.com/79301742/116194181-1d8d0180-a74e-11eb-9fba-12cb38a505ce.png)

not working 
Only these formats are not working and some of files are not opened :-  xls , xlsx , doc ,sxc, sxw , tif

**Comment by rashmi0301** [comment]
> > @FH-sandeepkaur1 now when i try to edit the form then created date is not appear
> > ![image](https://user-images.githubusercontent.com/79301742/116194181-1d8d0180-a74e-11eb-9fba-12cb38a505ce.png)
> 
> not working
> Only these formats are not working and some of files are not opened :- xls , xlsx , doc ,sxc, sxw , tif

NOT DONE

**Comment by rashmi0301** [comment]
above all points are done .. 1 point is pending i will create a new task for this
