### ISSUE TITLE
Route :- Not able to add Route 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#939]
![image](https://user-images.githubusercontent.com/79301742/114846373-43371400-9dfa-11eb-8cae-dc1d3397ce1d.png)

**Comment by rashmi0301** [comment]
WORking

**Comment by rashmi0301** [comment]
Again i am not able to add Route

**Comment by rashmi0301** [comment]
working ..

**Comment by rashmi0301** [comment]
hello @nameetjambla  route is not edited and working properly due to the disabled create route button

**Comment by robinhawks** [comment]
@FH-sandeepkaur1 please comment if its completed or in process 
@rashmi0301 Test it and do not close until its Done !

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 is working on that if its done then i will do testing . 
i will close after the testing . @robinhawks

**Comment by rashmi0301** [comment]
route is added with multiple stops and modals are also working . 
editing is also working 
check  entry this 
![image](https://user-images.githubusercontent.com/79301742/119238271-64c0a500-baf6-11eb-894c-ff958e01b3a1.png)
