### ISSUE TITLE
Cross border :- Searching Filter of Trip number and port of entry is not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#940]
Scenario is that :- 

1. Trip number -- suggestions are not occur , when entered small letters then searching data is not appear 
2. Port of entry is not in list view . so if we want to search the port of entry we have to go to editing or detail page to know what's the data of the port of entry ?

**Comment by FH-sandeepkaur1** [comment]
Suggestions are not there as it is a category based search.

**Comment by rashmi0301** [comment]
cross border will check on next working day

**Comment by rashmi0301** [comment]
Port of entry is not in list view . so if we want to search the port of entry we have to go to editing or detail page to know what's the data of the port of entry ?

how can i check ?

**Comment by FH-sandeepkaur1** [comment]
Port of entry is now there in listing

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/116238613-34981780-a77f-11eb-8b87-eedbfa450699.png)

For new record

**Comment by rashmi0301** [comment]
okay i will do tomm . by adding a new entry

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/118499914-3436d080-b6dc-11eb-912a-8b09cd34f3f6.png)

not working 

pagination also not working

**Comment by robinhawks** [comment]
@Hardeep8587 @FH-sandeepkaur1 comment if you have done any point so we should know who worked on it !

**Comment by Hardeep8587** [comment]
@rashmi0301 please check devapp, trip number search and ports are showing

**Comment by rashmi0301** [comment]
> ![image](https://user-images.githubusercontent.com/79301742/118499914-3436d080-b6dc-11eb-912a-8b09cd34f3f6.png)
> 
> not working
> 
> pagination also not working

yes this is showing .. but searching not working

**Comment by rashmi0301** [comment]
checked in ace -- this is working 
ACI -- working
