### ISSUE TITLE
Order :- Order number and location filters are not working 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#941]
![image](https://user-images.githubusercontent.com/79301742/114851550-965f9580-9dff-11eb-8c0b-ed5a6d8ba6ee.png)

1. suggestions are not occur .
2.  For location if i had entered full pickup location in caps and small then searching data and suggestions are not occur

**Comment by FH-sandeepkaur1** [comment]
Suggestions are not shown here as it a category based search

**Comment by rashmi0301** [comment]
Today i m working on address book part .. will check Dispatch by tomm

**Comment by rashmi0301** [comment]
Order number searching filter is not working

**Comment by rashmi0301** [comment]
NOT WORKING checked over the new record

**Comment by rashmi0301** [comment]
order filters are working
