### ISSUE TITLE
Disable the submit/update button when it is clicked in whole product

### ISSUE THREAD

**Issue by FH-sandeepkaur1** [Fleet-Hawks-Inc/fh-cloud-app#946]
The button should be disabled when the user clicks on it to avoid duplicate entries.

**Comment by FH-sandeepkaur1** [comment]
done in driver, vehicle, asset, fuel, reminders, address book

**Comment by AmitojSingh1** [comment]
What's pending? @FH-sandeepkaur1 @rashmi0301

**Comment by robinhawks** [comment]
@rashmi0301 what is pending in this  ? why you haven't Tested yet

**Comment by rashmi0301** [comment]
now the buttons are disabled like save and update
but when you fill the required fields with valid data then it is enable 

except trips -- no need to do this here
