### ISSUE TITLE
Service log :- error occur 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#959]
![image](https://user-images.githubusercontent.com/79301742/115105882-48719b80-9f7f-11eb-98c4-768d05754e92.png)

when i am entering the existing part

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115105953-8b337380-9f7f-11eb-82f5-2195fd4de30e.png)

**Comment by rashmi0301** [comment]
Not able to add also 

![image](https://user-images.githubusercontent.com/79301742/115105985-b9b14e80-9f7f-11eb-9653-0074bcd1fb45.png)

**Comment by Hardeep8587** [comment]
Done check it out in devapp

**Comment by rashmi0301** [comment]
DONE
