### ISSUE TITLE
Issue tab :- validation exception error occur 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#962]
when our issue is in asset then we want to resolve through service log .. and hit on save button then validation exception occur 

![image](https://user-images.githubusercontent.com/79301742/115109356-fcc8ed00-9f92-11eb-984e-08da9deefa9c.png)

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115868928-cc81c280-a45a-11eb-937f-c8f79fc62974.png)



when are going through asset to resolve the issue in service log then error occur 
when we are going through vehicle and asset to resolve the issue but when we are not selected the issue then it gives error to show that please select the issue to resolve 
-- on that page those issues are already resolved and closed that should not appear on service log

**Comment by rashmi0301** [comment]
any update ?

**Comment by rashmi0301** [comment]
On detail pages of issue tab 

resolve button is disable now for resolved issues 
closed and open -- resolve button is enable

**Comment by robinhawks** [comment]
@Hardeep8587 @FH-sandeepkaur1 @rashmi0301 
who is working on which points Any update ?

**Comment by rashmi0301** [comment]
1 validation exception error is still there . 
2. After resolving the service log issues then these are occurred :- On detail pages of issue tab

resolve button is disable now for resolved issues
closed and open -- resolve button is enable

**Comment by Hardeep8587** [comment]
@rashmi0301  please verify

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 is doing the schema changes . after this then i will do proper testing of this issue

**Comment by rashmi0301** [comment]
1. validation exception error --- Resolved 

2. when we are going through vehicle and asset to resolve the issue but when we are not selected the issue then it gives error to show that please select the issue to resolve --- No need as per the discussion @Daljit-fleetHawks 

3. on that page those issues are already resolved and closed that should not appear on service log --- DONE now only open issues are appear on service log with respective vehicle and asset 

4. After resolving the service log issues then these are occurred :- On detail pages of issue tab
resolve button is disable now for resolved issues
closed and open -- resolve button is enable  ---- DONE  now for closed and resolved issues -- Resolved button is appear for a while when the page is loading then it  is not appear
