### ISSUE TITLE
Issue tab :- Alignment issue

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#963]
![image](https://user-images.githubusercontent.com/79301742/115109675-d2782f00-9f94-11eb-8213-1d49e92a9a6e.png)

**Comment by pankaj-fleethawks** [comment]
Its done @rashmi0301 check .. at your end

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/115511648-b29b8080-a29e-11eb-9f78-23c10738fdab.png)

why this spacing occur

**Comment by pankaj-fleethawks** [comment]
@rashmi0301 done this.. check now.. i am sharing screen also

**Comment by pankaj-fleethawks** [comment]
![image](https://user-images.githubusercontent.com/63699936/115589970-14cfa200-a2ee-11eb-9fed-65dfd9683379.png)

**Comment by rashmi0301** [comment]
done
