### ISSUE TITLE
Reminders :- Email notification 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#972]
if we select group then email notification how it works ?

![image](https://user-images.githubusercontent.com/79301742/115220312-03d43480-a126-11eb-8cac-1e010c631315.png)

**Comment by rashmi0301** [comment]
any update ?

**Comment by rashmi0301** [comment]
1, due date now -- depend upon eld 
2. overdue and due soon status -- how it comes / works , 
3. when on edit page then last odometer and last service date is not appear 
4. groups and users where are these coming from ? 
5. if we click on plus icon then here if we add group members and description where it save and where it is showing . This point is applicable for all group and type plus icons in our modules

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/118364078-d4a9bb00-b54b-11eb-9242-0712dda1768b.png)

**Comment by robinhawks** [comment]
@FH-sandeepkaur1 @rashmi0301 

Any Update ?

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 is working on that . please wait for her approval

**Comment by rashmi0301** [comment]
We are receiving the emails now
