### ISSUE TITLE
Contact Reminder :- Type is not showing on list page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#974]
![image](https://user-images.githubusercontent.com/79301742/115222575-7fcf7c00-a128-11eb-8202-6941649002d4.png)

**Comment by rashmi0301** [comment]
Reminders is in under discussion as per the discussed with sandeep

**Comment by rashmi0301** [comment]
any update regarding full reminders

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/118269163-3a764400-b473-11eb-8a07-25e5ee016904.png)

type is not showing

**Comment by Hardeep8587** [comment]
@rashmi0301 m working on this

**Comment by robinhawks** [comment]
> ![image](https://user-images.githubusercontent.com/79301742/118269163-3a764400-b473-11eb-8a07-25e5ee016904.png)
> 
> type is not showing

@rashmi0301 Test after completion try to finish this issue as its pending from almost a month now !

**Comment by rashmi0301** [comment]
Type is showing now . 

![image](https://user-images.githubusercontent.com/79301742/119032755-64db6c00-b961-11eb-8e2e-1b71a6c99379.png)
