### ISSUE TITLE
Fuel :- Reefer

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#986]
![image](https://user-images.githubusercontent.com/79301742/115348255-07bc9100-a1d0-11eb-933f-347835e266fc.png)

i am not  able to select the reefer data

**Comment by Hardeep8587** [comment]
need to add asset of type reefer

**Comment by rashmi0301** [comment]
added asset with reefer type but still i am not getting the reefer data

**Comment by rashmi0301** [comment]
added asset with reefer type Now i am getting the reefer data
