### ISSUE TITLE
Border connect :- error occur on ACI

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#999]
![image](https://user-images.githubusercontent.com/79301742/115676550-50f61780-a36d-11eb-99b7-77a84a788c1c.png)

when  i am adding the extra shipment and hits on other buttons from detail to add data then on add page this type of error occur

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/116238216-b89dcf80-a77e-11eb-9a81-06b5e0d556f3.png)

**Comment by rashmi0301** [comment]
I am not getting the details on detail page now and while editing Type error receiver and type error to upper case is occur .

**Comment by Hardeep8587** [comment]
@rashmi0301 please check now

**Comment by rashmi0301** [comment]
done
